import dns from 'dns';
import mongoose from 'mongoose';
import dotenv from 'dotenv';
import Question from './models/Question.js';
import User from './models/User.js';

try {
  dns.setServers(['8.8.8.8', '1.1.1.1']);
} catch (e) {}

dotenv.config();


const questions = [
  // ===================== APTITUDE - Quantitative =====================
  {
    title: 'Profit and Loss Percentage',
    category: 'aptitude',
    subject: 'Quantitative Aptitude',
    topic: 'Profit and Loss',
    difficulty: 'easy',
    type: 'mcq',
    question: 'A shopkeeper buys an article for ₹500 and sells it for ₹600. What is the profit percentage?',
    options: ['15%', '20%', '25%', '10%'],
    correctAnswer: '20%',
    explanation: 'Profit = 600 - 500 = ₹100. Profit% = (100/500) × 100 = 20%.',
    tags: ['profit-loss', 'percentage', 'arithmetic'],
  },
  {
    title: 'Simple Interest Calculation',
    category: 'aptitude',
    subject: 'Quantitative Aptitude',
    topic: 'Simple Interest',
    difficulty: 'easy',
    type: 'mcq',
    question: 'Find the simple interest on ₹5000 at 8% per annum for 3 years.',
    options: ['₹1200', '₹1000', '₹800', '₹1500'],
    correctAnswer: '₹1200',
    explanation: 'SI = P × R × T / 100 = 5000 × 8 × 3 / 100 = ₹1200.',
    tags: ['simple-interest', 'arithmetic'],
  },
  {
    title: 'Average of Numbers',
    category: 'aptitude',
    subject: 'Quantitative Aptitude',
    topic: 'Averages',
    difficulty: 'easy',
    type: 'mcq',
    question: 'The average of 5 consecutive odd numbers starting from 3 is:',
    options: ['5', '7', '9', '11'],
    correctAnswer: '7',
    explanation: 'The numbers are 3, 5, 7, 9, 11. Average = (3+5+7+9+11)/5 = 35/5 = 7.',
    tags: ['averages', 'arithmetic'],
  },
  {
    title: 'Time and Work Problem',
    category: 'aptitude',
    subject: 'Quantitative Aptitude',
    topic: 'Time and Work',
    difficulty: 'medium',
    type: 'mcq',
    question: 'A can do a work in 15 days and B can do it in 20 days. If they work together, in how many days will they finish the work?',
    options: ['8 4/7 days', '7 days', '9 days', '10 days'],
    correctAnswer: '8 4/7 days',
    explanation: 'A\'s 1 day work = 1/15, B\'s 1 day work = 1/20. Combined = 1/15 + 1/20 = 7/60. Days = 60/7 = 8 4/7 days.',
    tags: ['time-work', 'fractions'],
  },
  {
    title: 'Speed Distance Time',
    category: 'aptitude',
    subject: 'Quantitative Aptitude',
    topic: 'Speed Distance Time',
    difficulty: 'medium',
    type: 'mcq',
    question: 'A train 200m long crosses a platform 300m long in 25 seconds. What is the speed of the train in km/hr?',
    options: ['72 km/hr', '60 km/hr', '80 km/hr', '54 km/hr'],
    correctAnswer: '72 km/hr',
    explanation: 'Total distance = 200 + 300 = 500m. Speed = 500/25 = 20 m/s = 20 × 18/5 = 72 km/hr.',
    tags: ['speed', 'distance', 'trains'],
  },
  {
    title: 'Compound Interest',
    category: 'aptitude',
    subject: 'Quantitative Aptitude',
    topic: 'Compound Interest',
    difficulty: 'hard',
    type: 'mcq',
    question: 'Find the compound interest on ₹10000 at 10% per annum for 2 years compounded annually.',
    options: ['₹2100', '₹2000', '₹1900', '₹2200'],
    correctAnswer: '₹2100',
    explanation: 'A = P(1 + R/100)^n = 10000(1.1)^2 = ₹12100. CI = 12100 - 10000 = ₹2100.',
    tags: ['compound-interest', 'arithmetic'],
  },
  {
    title: 'Ratio and Proportion',
    category: 'aptitude',
    subject: 'Quantitative Aptitude',
    topic: 'Ratio and Proportion',
    difficulty: 'easy',
    type: 'mcq',
    question: 'If A:B = 3:4 and B:C = 5:6, then A:B:C is:',
    options: ['15:20:24', '3:4:6', '9:12:16', '15:20:18'],
    correctAnswer: '15:20:24',
    explanation: 'A:B = 3:4 = 15:20 and B:C = 5:6 = 20:24. Therefore A:B:C = 15:20:24.',
    tags: ['ratio', 'proportion'],
  },
  {
    title: 'Percentage Increase',
    category: 'aptitude',
    subject: 'Quantitative Aptitude',
    topic: 'Percentages',
    difficulty: 'easy',
    type: 'mcq',
    question: 'If a number is increased by 25% and the resulting number is then decreased by 20%, the overall change is:',
    options: ['0%', '5% increase', '5% decrease', '10% increase'],
    correctAnswer: '0%',
    explanation: 'Let x be the number. After 25% increase: 1.25x. After 20% decrease: 1.25x × 0.8 = x. Net change = 0%.',
    tags: ['percentages', 'arithmetic'],
  },

  // ===================== APTITUDE - Logical Reasoning =====================
  {
    title: 'Number Series Pattern',
    category: 'aptitude',
    subject: 'Logical Reasoning',
    topic: 'Number Series',
    difficulty: 'easy',
    type: 'mcq',
    question: 'What comes next in the series: 2, 6, 12, 20, 30, ?',
    options: ['42', '40', '38', '44'],
    correctAnswer: '42',
    explanation: 'Differences: 4, 6, 8, 10, 12. The next number is 30 + 12 = 42. Pattern: n(n+1) where n=1,2,3...',
    tags: ['number-series', 'pattern'],
  },
  {
    title: 'Blood Relations',
    category: 'aptitude',
    subject: 'Logical Reasoning',
    topic: 'Blood Relations',
    difficulty: 'medium',
    type: 'mcq',
    question: 'Pointing to a man, a woman said, "His mother is the only daughter of my mother." How is the woman related to the man?',
    options: ['Mother', 'Grandmother', 'Sister', 'Aunt'],
    correctAnswer: 'Mother',
    explanation: 'The only daughter of my mother = the woman herself. So the man\'s mother is the woman. She is his mother.',
    tags: ['blood-relations', 'reasoning'],
  },
  {
    title: 'Coding-Decoding',
    category: 'aptitude',
    subject: 'Logical Reasoning',
    topic: 'Coding-Decoding',
    difficulty: 'medium',
    type: 'mcq',
    question: 'If COMPUTER is coded as RFUVQNPD, how is MEDICINE coded?',
    options: ['FNDJDJEM', 'EDJDJEFN', 'FOJEJEFN', 'FNJEDJEM'],
    correctAnswer: 'FNDJDJEM',
    explanation: 'The word is reversed and each letter is shifted by +1. COMPUTER → RETUPMOC → +1 → RFUVQNPD. MEDICINE → ENIDICM → +1 → FNDJDJEM.',
    tags: ['coding-decoding', 'reasoning'],
  },
  {
    title: 'Syllogism',
    category: 'aptitude',
    subject: 'Logical Reasoning',
    topic: 'Syllogisms',
    difficulty: 'hard',
    type: 'mcq',
    question: 'Statements: All dogs are animals. All animals are living beings. Conclusions: I. All dogs are living beings. II. All living beings are dogs.',
    options: ['Only I follows', 'Only II follows', 'Both follow', 'Neither follows'],
    correctAnswer: 'Only I follows',
    explanation: 'From the chain: Dogs ⊂ Animals ⊂ Living beings, so all dogs are living beings (I follows). But not all living beings are dogs (II does not follow).',
    tags: ['syllogism', 'logic'],
  },
  {
    title: 'Direction Sense',
    category: 'aptitude',
    subject: 'Logical Reasoning',
    topic: 'Direction Sense',
    difficulty: 'easy',
    type: 'mcq',
    question: 'Ravi walks 10m towards North, then turns right and walks 15m, then turns right and walks 10m. In which direction is he facing now?',
    options: ['South', 'East', 'West', 'North'],
    correctAnswer: 'South',
    explanation: 'Starting North → Right turn = East (15m) → Right turn = South (10m). He is facing South.',
    tags: ['direction', 'reasoning'],
  },

  // ===================== APTITUDE - Verbal Ability =====================
  {
    title: 'Synonym Identification',
    category: 'aptitude',
    subject: 'Verbal Ability',
    topic: 'Synonyms',
    difficulty: 'easy',
    type: 'mcq',
    question: 'Choose the synonym of "Eloquent":',
    options: ['Articulate', 'Silent', 'Rude', 'Modest'],
    correctAnswer: 'Articulate',
    explanation: 'Eloquent means fluent and persuasive in speaking or writing. Articulate has a similar meaning.',
    tags: ['synonyms', 'vocabulary'],
  },
  {
    title: 'Antonym Identification',
    category: 'aptitude',
    subject: 'Verbal Ability',
    topic: 'Antonyms',
    difficulty: 'easy',
    type: 'mcq',
    question: 'Choose the antonym of "Benevolent":',
    options: ['Malevolent', 'Kind', 'Generous', 'Friendly'],
    correctAnswer: 'Malevolent',
    explanation: 'Benevolent means well-meaning and kindly. Malevolent means having ill will, the opposite.',
    tags: ['antonyms', 'vocabulary'],
  },
  {
    title: 'Sentence Correction',
    category: 'aptitude',
    subject: 'Verbal Ability',
    topic: 'Grammar',
    difficulty: 'medium',
    type: 'mcq',
    question: 'Choose the correct sentence:',
    options: [
      'Neither the students nor the teacher was present.',
      'Neither the students nor the teacher were present.',
      'Neither the students or the teacher was present.',
      'Neither the students or the teacher were present.',
    ],
    correctAnswer: 'Neither the students nor the teacher was present.',
    explanation: 'With "neither...nor", the verb agrees with the subject closest to it. "Teacher" is singular, so "was" is correct.',
    tags: ['grammar', 'sentence-correction'],
  },
  {
    title: 'Reading Comprehension',
    category: 'aptitude',
    subject: 'Verbal Ability',
    topic: 'Reading Comprehension',
    difficulty: 'medium',
    type: 'mcq',
    question: 'Passage: "Climate change is the defining crisis of our time. The science is clear: we need to halve emissions by 2030." What is the main idea?',
    options: [
      'Urgent need to reduce emissions',
      'Climate is not changing',
      'Science is uncertain about climate',
      'Emissions will halve automatically',
    ],
    correctAnswer: 'Urgent need to reduce emissions',
    explanation: 'The passage emphasizes the urgency ("defining crisis") and the specific action needed ("halve emissions by 2030").',
    tags: ['reading-comprehension', 'verbal'],
  },

  // ===================== TECHNICAL - JavaScript =====================
  {
    title: 'JavaScript Closures',
    category: 'technical',
    subject: 'JavaScript',
    topic: 'Closures',
    difficulty: 'medium',
    type: 'mcq',
    question: 'What is the output? function outer() { let count = 0; return function() { return ++count; }; } const fn = outer(); console.log(fn(), fn(), fn());',
    options: ['1 2 3', '1 1 1', '0 1 2', 'undefined'],
    correctAnswer: '1 2 3',
    explanation: 'The inner function forms a closure over the `count` variable. Each call increments and returns the same `count` variable: 1, 2, 3.',
    tags: ['closures', 'javascript', 'scope'],
  },
  {
    title: 'JavaScript Promises',
    category: 'technical',
    subject: 'JavaScript',
    topic: 'Promises',
    difficulty: 'medium',
    type: 'mcq',
    question: 'What is the output? console.log("1"); setTimeout(() => console.log("2"), 0); Promise.resolve().then(() => console.log("3")); console.log("4");',
    options: ['1 4 3 2', '1 2 3 4', '1 4 2 3', '1 3 4 2'],
    correctAnswer: '1 4 3 2',
    explanation: 'Synchronous code runs first (1, 4). Microtasks (Promises) run before macrotasks (setTimeout). So 3 before 2.',
    tags: ['promises', 'event-loop', 'javascript'],
  },
  {
    title: 'JavaScript var vs let',
    category: 'technical',
    subject: 'JavaScript',
    topic: 'Variables',
    difficulty: 'easy',
    type: 'mcq',
    question: 'What is the key difference between "let" and "var" in JavaScript?',
    options: [
      'let is block-scoped, var is function-scoped',
      'var is block-scoped, let is function-scoped',
      'Both are block-scoped',
      'Both are function-scoped',
    ],
    correctAnswer: 'let is block-scoped, var is function-scoped',
    explanation: '`let` and `const` are block-scoped (confined to the {} block). `var` is function-scoped and gets hoisted.',
    tags: ['variables', 'scope', 'javascript'],
  },
  {
    title: 'Array Methods',
    category: 'technical',
    subject: 'JavaScript',
    topic: 'Arrays',
    difficulty: 'easy',
    type: 'mcq',
    question: 'Which array method returns a new array with elements that pass a test?',
    options: ['filter()', 'map()', 'reduce()', 'forEach()'],
    correctAnswer: 'filter()',
    explanation: 'filter() creates a new array with elements that pass the provided function\'s test. map() transforms, reduce() accumulates, forEach() just iterates.',
    tags: ['arrays', 'methods', 'javascript'],
  },
  {
    title: 'this keyword in JavaScript',
    category: 'technical',
    subject: 'JavaScript',
    topic: 'this keyword',
    difficulty: 'hard',
    type: 'mcq',
    question: 'In an arrow function, what does "this" refer to?',
    options: [
      'The enclosing lexical context',
      'The global object',
      'The function itself',
      'undefined always',
    ],
    correctAnswer: 'The enclosing lexical context',
    explanation: 'Arrow functions do not have their own `this`. They inherit `this` from the enclosing lexical scope (where they are defined).',
    tags: ['this', 'arrow-functions', 'javascript'],
  },

  // ===================== TECHNICAL - Python =====================
  {
    title: 'Python List Comprehension',
    category: 'technical',
    subject: 'Python',
    topic: 'List Comprehension',
    difficulty: 'easy',
    type: 'mcq',
    question: 'What is the output of: [x**2 for x in range(5)]?',
    options: ['[0, 1, 4, 9, 16]', '[1, 4, 9, 16, 25]', '[0, 1, 2, 3, 4]', '[1, 2, 3, 4, 5]'],
    correctAnswer: '[0, 1, 4, 9, 16]',
    explanation: 'range(5) generates 0,1,2,3,4. Each is squared: 0,1,4,9,16.',
    tags: ['list-comprehension', 'python'],
  },
  {
    title: 'Python Decorators',
    category: 'technical',
    subject: 'Python',
    topic: 'Decorators',
    difficulty: 'hard',
    type: 'mcq',
    question: 'What is a decorator in Python?',
    options: [
      'A function that takes another function and extends its behavior',
      'A class that inherits from another class',
      'A variable that holds a function',
      'A loop that iterates over functions',
    ],
    correctAnswer: 'A function that takes another function and extends its behavior',
    explanation: 'Decorators wrap a function to modify its behavior without changing its source code. They use @decorator_name syntax.',
    tags: ['decorators', 'python', 'functions'],
  },
  {
    title: 'Python GIL',
    category: 'technical',
    subject: 'Python',
    topic: 'GIL',
    difficulty: 'hard',
    type: 'mcq',
    question: 'What is the Global Interpreter Lock (GIL) in Python?',
    options: [
      'A mutex that prevents multiple threads from executing Python bytecodes simultaneously',
      'A lock on global variables',
      'A security feature for file access',
      'A mechanism for garbage collection',
    ],
    correctAnswer: 'A mutex that prevents multiple threads from executing Python bytecodes simultaneously',
    explanation: 'The GIL is a mutex in CPython that allows only one thread to hold control of the Python interpreter at a time.',
    tags: ['gil', 'threading', 'python'],
  },
  {
    title: 'Python Mutable vs Immutable',
    category: 'technical',
    subject: 'Python',
    topic: 'Data Types',
    difficulty: 'easy',
    type: 'mcq',
    question: 'Which of the following is immutable in Python?',
    options: ['Tuple', 'List', 'Dictionary', 'Set'],
    correctAnswer: 'Tuple',
    explanation: 'Tuples are immutable — once created, their elements cannot be changed. Lists, dictionaries, and sets are mutable.',
    tags: ['data-types', 'immutable', 'python'],
  },

  // ===================== TECHNICAL - Java =====================
  {
    title: 'Java OOP - Abstraction',
    category: 'technical',
    subject: 'Java',
    topic: 'OOP',
    difficulty: 'medium',
    type: 'mcq',
    question: 'Which of the following achieves abstraction in Java?',
    options: [
      'Abstract classes and interfaces',
      'Only abstract classes',
      'Only interfaces',
      'Concrete classes only',
    ],
    correctAnswer: 'Abstract classes and interfaces',
    explanation: 'Both abstract classes (partial abstraction) and interfaces (full abstraction) achieve abstraction in Java.',
    tags: ['oop', 'abstraction', 'java'],
  },
  {
    title: 'Java Collections Framework',
    category: 'technical',
    subject: 'Java',
    topic: 'Collections',
    difficulty: 'medium',
    type: 'mcq',
    question: 'Which Java collection does not allow duplicate elements?',
    options: ['HashSet', 'ArrayList', 'LinkedList', 'Vector'],
    correctAnswer: 'HashSet',
    explanation: 'HashSet implements the Set interface which does not allow duplicate elements. List implementations (ArrayList, LinkedList, Vector) allow duplicates.',
    tags: ['collections', 'set', 'java'],
  },
  {
    title: 'Java Exception Handling',
    category: 'technical',
    subject: 'Java',
    topic: 'Exceptions',
    difficulty: 'easy',
    type: 'mcq',
    question: 'What is the difference between checked and unchecked exceptions in Java?',
    options: [
      'Checked exceptions must be caught or declared; unchecked don\'t need to be',
      'Unchecked exceptions must be caught; checked don\'t need to be',
      'Both must be caught',
      'Neither needs to be caught',
    ],
    correctAnswer: 'Checked exceptions must be caught or declared; unchecked don\'t need to be',
    explanation: 'Checked exceptions (like IOException) must be handled at compile time. Unchecked exceptions (like NullPointerException) are runtime exceptions.',
    tags: ['exceptions', 'error-handling', 'java'],
  },

  // ===================== TECHNICAL - C/C++ =====================
  {
    title: 'C Pointers Basics',
    category: 'technical',
    subject: 'C',
    topic: 'Pointers',
    difficulty: 'medium',
    type: 'mcq',
    question: 'What does the following code print? int x = 10; int *p = &x; printf("%d", *p);',
    options: ['10', 'Address of x', 'Garbage value', 'Compilation error'],
    correctAnswer: '10',
    explanation: '*p dereferences the pointer p, which points to x. So *p gives the value of x, which is 10.',
    tags: ['pointers', 'c'],
  },
  {
    title: 'C++ Virtual Functions',
    category: 'technical',
    subject: 'C++',
    topic: 'Virtual Functions',
    difficulty: 'hard',
    type: 'mcq',
    question: 'What is the purpose of virtual functions in C++?',
    options: [
      'To achieve runtime polymorphism',
      'To achieve compile-time polymorphism',
      'To prevent inheritance',
      'To make functions static',
    ],
    correctAnswer: 'To achieve runtime polymorphism',
    explanation: 'Virtual functions enable runtime (dynamic) polymorphism through vtable mechanism, allowing derived class methods to be called via base class pointers.',
    tags: ['virtual-functions', 'polymorphism', 'cpp'],
  },

  // ===================== TECHNICAL - DBMS =====================
  {
    title: 'SQL Joins',
    category: 'technical',
    subject: 'DBMS',
    topic: 'SQL Joins',
    difficulty: 'medium',
    type: 'mcq',
    question: 'Which SQL JOIN returns all rows from the left table and matched rows from the right table?',
    options: ['LEFT JOIN', 'RIGHT JOIN', 'INNER JOIN', 'CROSS JOIN'],
    correctAnswer: 'LEFT JOIN',
    explanation: 'LEFT JOIN returns all records from the left table and matched records from the right table. Unmatched right table columns are NULL.',
    tags: ['sql', 'joins', 'dbms'],
  },
  {
    title: 'Database Normalization',
    category: 'technical',
    subject: 'DBMS',
    topic: 'Normalization',
    difficulty: 'medium',
    type: 'mcq',
    question: 'Which normal form eliminates transitive dependencies?',
    options: ['3NF', '1NF', '2NF', 'BCNF'],
    correctAnswer: '3NF',
    explanation: 'Third Normal Form (3NF) requires no transitive dependencies — every non-key attribute must depend on the primary key directly.',
    tags: ['normalization', 'dbms'],
  },
  {
    title: 'ACID Properties',
    category: 'technical',
    subject: 'DBMS',
    topic: 'Transactions',
    difficulty: 'easy',
    type: 'mcq',
    question: 'What does the "I" in ACID properties stand for?',
    options: ['Isolation', 'Integration', 'Initialization', 'Iteration'],
    correctAnswer: 'Isolation',
    explanation: 'ACID: Atomicity, Consistency, Isolation, Durability. Isolation ensures concurrent transactions don\'t interfere with each other.',
    tags: ['acid', 'transactions', 'dbms'],
  },

  // ===================== TECHNICAL - Operating System =====================
  {
    title: 'Process vs Thread',
    category: 'technical',
    subject: 'Operating System',
    topic: 'Processes',
    difficulty: 'easy',
    type: 'mcq',
    question: 'What is the main difference between a process and a thread?',
    options: [
      'Threads share memory space; processes have separate memory',
      'Processes share memory space; threads have separate memory',
      'Both share the same memory',
      'Neither shares memory',
    ],
    correctAnswer: 'Threads share memory space; processes have separate memory',
    explanation: 'Threads within a process share the same memory space and resources. Separate processes have independent memory spaces.',
    tags: ['process', 'thread', 'os'],
  },
  {
    title: 'Deadlock Conditions',
    category: 'technical',
    subject: 'Operating System',
    topic: 'Deadlock',
    difficulty: 'medium',
    type: 'mcq',
    question: 'Which is NOT a necessary condition for deadlock?',
    options: ['Preemption', 'Mutual Exclusion', 'Hold and Wait', 'Circular Wait'],
    correctAnswer: 'Preemption',
    explanation: 'The four necessary conditions are: Mutual Exclusion, Hold and Wait, No Preemption, and Circular Wait. "No Preemption" (not "Preemption") is the condition.',
    tags: ['deadlock', 'os'],
  },
  {
    title: 'Page Replacement - LRU',
    category: 'technical',
    subject: 'Operating System',
    topic: 'Memory Management',
    difficulty: 'hard',
    type: 'mcq',
    question: 'In LRU page replacement algorithm, which page is replaced?',
    options: [
      'The page that has not been used for the longest time',
      'The page that was loaded first',
      'A random page',
      'The most frequently used page',
    ],
    correctAnswer: 'The page that has not been used for the longest time',
    explanation: 'LRU (Least Recently Used) replaces the page that has not been used for the longest period of time.',
    tags: ['paging', 'lru', 'os'],
  },

  // ===================== TECHNICAL - Computer Networks =====================
  {
    title: 'OSI Model Layers',
    category: 'technical',
    subject: 'Computer Networks',
    topic: 'OSI Model',
    difficulty: 'easy',
    type: 'mcq',
    question: 'How many layers are in the OSI model?',
    options: ['7', '5', '4', '6'],
    correctAnswer: '7',
    explanation: 'The OSI model has 7 layers: Physical, Data Link, Network, Transport, Session, Presentation, and Application.',
    tags: ['osi', 'layers', 'networking'],
  },
  {
    title: 'TCP vs UDP',
    category: 'technical',
    subject: 'Computer Networks',
    topic: 'Transport Layer',
    difficulty: 'easy',
    type: 'mcq',
    question: 'Which protocol provides reliable, ordered delivery of data?',
    options: ['TCP', 'UDP', 'IP', 'ICMP'],
    correctAnswer: 'TCP',
    explanation: 'TCP (Transmission Control Protocol) provides reliable, ordered, and error-checked delivery. UDP is connectionless and unreliable but faster.',
    tags: ['tcp', 'udp', 'networking'],
  },

  // ===================== TECHNICAL - OOP =====================
  {
    title: 'Pillars of OOP',
    category: 'technical',
    subject: 'OOP',
    topic: 'Fundamentals',
    difficulty: 'easy',
    type: 'mcq',
    question: 'Which of the following is NOT a pillar of Object-Oriented Programming?',
    options: ['Compilation', 'Encapsulation', 'Inheritance', 'Polymorphism'],
    correctAnswer: 'Compilation',
    explanation: 'The four pillars of OOP are: Encapsulation, Abstraction, Inheritance, and Polymorphism. Compilation is not an OOP concept.',
    tags: ['oop', 'fundamentals'],
  },

  // ===================== TECHNICAL - SQL =====================
  {
    title: 'SQL GROUP BY',
    category: 'technical',
    subject: 'SQL',
    topic: 'Aggregation',
    difficulty: 'medium',
    type: 'mcq',
    question: 'What is the purpose of GROUP BY clause in SQL?',
    options: [
      'To group rows that have the same values in specified columns',
      'To sort the result set',
      'To filter rows',
      'To join tables',
    ],
    correctAnswer: 'To group rows that have the same values in specified columns',
    explanation: 'GROUP BY groups rows with the same values into summary rows, often used with aggregate functions (COUNT, SUM, AVG, etc.).',
    tags: ['sql', 'group-by', 'aggregation'],
  },

  // ===================== TECHNICAL - Software Engineering =====================
  {
    title: 'Agile vs Waterfall',
    category: 'technical',
    subject: 'Software Engineering',
    topic: 'SDLC',
    difficulty: 'easy',
    type: 'mcq',
    question: 'What is the key advantage of Agile over Waterfall methodology?',
    options: [
      'Flexibility to accommodate changes during development',
      'Better documentation',
      'Simpler project management',
      'Lower cost',
    ],
    correctAnswer: 'Flexibility to accommodate changes during development',
    explanation: 'Agile emphasizes iterative development and accommodating changes. Waterfall follows a linear, sequential approach with rigid phases.',
    tags: ['agile', 'waterfall', 'sdlc'],
  },

  // ===================== TECHNICAL - Machine Learning Basics =====================
  {
    title: 'Supervised vs Unsupervised Learning',
    category: 'technical',
    subject: 'Machine Learning Basics',
    topic: 'ML Types',
    difficulty: 'easy',
    type: 'mcq',
    question: 'What distinguishes supervised learning from unsupervised learning?',
    options: [
      'Supervised learning uses labeled data; unsupervised uses unlabeled data',
      'Unsupervised learning uses labeled data; supervised uses unlabeled data',
      'Both use labeled data',
      'Both use unlabeled data',
    ],
    correctAnswer: 'Supervised learning uses labeled data; unsupervised uses unlabeled data',
    explanation: 'In supervised learning, the model trains on labeled data (input-output pairs). Unsupervised learning finds patterns in unlabeled data.',
    tags: ['ml', 'supervised', 'unsupervised'],
  },

  // ===================== DSA - Arrays =====================
  {
    title: 'Two Sum Problem',
    category: 'dsa',
    subject: 'Arrays',
    topic: 'Arrays',
    difficulty: 'easy',
    type: 'mcq',
    question: 'What is the optimal time complexity for the Two Sum problem (find two numbers that add up to a target)?',
    options: ['O(n)', 'O(n²)', 'O(n log n)', 'O(1)'],
    correctAnswer: 'O(n)',
    explanation: 'Using a hash map, you can solve Two Sum in O(n) time by storing each number and checking if (target - current) exists.',
    tags: ['arrays', 'hash-map', 'two-sum'],
  },
  {
    title: 'Maximum Subarray (Kadane\'s)',
    category: 'dsa',
    subject: 'Arrays',
    topic: 'Arrays',
    difficulty: 'medium',
    type: 'mcq',
    question: 'Kadane\'s algorithm is used to find:',
    options: [
      'Maximum sum contiguous subarray',
      'Minimum element in array',
      'Sorted subarray',
      'Second largest element',
    ],
    correctAnswer: 'Maximum sum contiguous subarray',
    explanation: 'Kadane\'s algorithm finds the maximum sum contiguous subarray in O(n) time using dynamic programming principles.',
    tags: ['kadane', 'dynamic-programming', 'arrays'],
  },

  // ===================== DSA - Strings =====================
  {
    title: 'String Palindrome Check',
    category: 'dsa',
    subject: 'Strings',
    topic: 'Strings',
    difficulty: 'easy',
    type: 'mcq',
    question: 'What is the most efficient approach to check if a string is a palindrome?',
    options: [
      'Two-pointer technique from both ends',
      'Reverse and compare',
      'Using a stack',
      'Using recursion',
    ],
    correctAnswer: 'Two-pointer technique from both ends',
    explanation: 'Two pointers (start and end) moving inward is O(n) time and O(1) space — the most efficient approach.',
    tags: ['palindrome', 'two-pointer', 'strings'],
  },

  // ===================== DSA - Linked List =====================
  {
    title: 'Detect Cycle in Linked List',
    category: 'dsa',
    subject: 'Linked List',
    topic: 'Linked List',
    difficulty: 'medium',
    type: 'mcq',
    question: 'Which algorithm is commonly used to detect a cycle in a linked list?',
    options: ['Floyd\'s Cycle Detection (Tortoise & Hare)', 'Binary Search', 'DFS', 'BFS'],
    correctAnswer: 'Floyd\'s Cycle Detection (Tortoise & Hare)',
    explanation: 'Floyd\'s algorithm uses two pointers (slow & fast). If they meet, a cycle exists. O(n) time, O(1) space.',
    tags: ['linked-list', 'cycle-detection', 'floyd'],
  },
  {
    title: 'Reverse a Linked List',
    category: 'dsa',
    subject: 'Linked List',
    topic: 'Linked List',
    difficulty: 'easy',
    type: 'mcq',
    question: 'What is the time complexity of reversing a singly linked list iteratively?',
    options: ['O(n)', 'O(n²)', 'O(log n)', 'O(1)'],
    correctAnswer: 'O(n)',
    explanation: 'Iterative reversal traverses each node once, changing next pointers. Time: O(n), Space: O(1).',
    tags: ['linked-list', 'reverse'],
  },

  // ===================== DSA - Stack =====================
  {
    title: 'Balanced Parentheses',
    category: 'dsa',
    subject: 'Stack',
    topic: 'Stack',
    difficulty: 'easy',
    type: 'mcq',
    question: 'Which data structure is best suited for checking balanced parentheses?',
    options: ['Stack', 'Queue', 'Array', 'Linked List'],
    correctAnswer: 'Stack',
    explanation: 'A stack naturally handles nested structures. Push opening brackets, pop for closing brackets, and check if stack is empty at end.',
    tags: ['stack', 'parentheses', 'balanced'],
  },

  // ===================== DSA - Queue =====================
  {
    title: 'Queue Implementation',
    category: 'dsa',
    subject: 'Queue',
    topic: 'Queue',
    difficulty: 'easy',
    type: 'mcq',
    question: 'What is the order of element processing in a Queue?',
    options: ['FIFO', 'LIFO', 'Random', 'Priority-based'],
    correctAnswer: 'FIFO',
    explanation: 'Queue follows First-In-First-Out (FIFO) principle. Elements are added at the rear and removed from the front.',
    tags: ['queue', 'fifo'],
  },

  // ===================== DSA - Trees =====================
  {
    title: 'BST Search Complexity',
    category: 'dsa',
    subject: 'Trees',
    topic: 'Binary Search Tree',
    difficulty: 'medium',
    type: 'mcq',
    question: 'What is the average time complexity for searching in a balanced BST?',
    options: ['O(log n)', 'O(n)', 'O(n²)', 'O(1)'],
    correctAnswer: 'O(log n)',
    explanation: 'In a balanced BST, each comparison eliminates half the tree, giving O(log n) average search time. Worst case (skewed) is O(n).',
    tags: ['bst', 'search', 'trees'],
  },
  {
    title: 'Tree Traversal Orders',
    category: 'dsa',
    subject: 'Trees',
    topic: 'Tree Traversal',
    difficulty: 'easy',
    type: 'mcq',
    question: 'In which traversal order is the root visited first?',
    options: ['Preorder', 'Inorder', 'Postorder', 'Level order'],
    correctAnswer: 'Preorder',
    explanation: 'Preorder: Root → Left → Right. Inorder: Left → Root → Right. Postorder: Left → Right → Root.',
    tags: ['traversal', 'preorder', 'trees'],
  },

  // ===================== DSA - Graphs =====================
  {
    title: 'BFS vs DFS',
    category: 'dsa',
    subject: 'Graphs',
    topic: 'Graph Traversal',
    difficulty: 'medium',
    type: 'mcq',
    question: 'Which graph traversal uses a queue?',
    options: ['BFS', 'DFS', 'Both', 'Neither'],
    correctAnswer: 'BFS',
    explanation: 'BFS (Breadth-First Search) uses a queue to explore neighbors level by level. DFS uses a stack (or recursion).',
    tags: ['bfs', 'dfs', 'graphs'],
  },
  {
    title: 'Dijkstra\'s Algorithm',
    category: 'dsa',
    subject: 'Graphs',
    topic: 'Shortest Path',
    difficulty: 'hard',
    type: 'mcq',
    question: 'Dijkstra\'s algorithm does NOT work correctly with:',
    options: ['Negative edge weights', 'Large graphs', 'Undirected graphs', 'Dense graphs'],
    correctAnswer: 'Negative edge weights',
    explanation: 'Dijkstra\'s algorithm assumes all edge weights are non-negative. For negative weights, use Bellman-Ford algorithm.',
    tags: ['dijkstra', 'shortest-path', 'graphs'],
  },

  // ===================== DSA - Recursion =====================
  {
    title: 'Recursion Base Case',
    category: 'dsa',
    subject: 'Recursion',
    topic: 'Recursion',
    difficulty: 'easy',
    type: 'mcq',
    question: 'What happens if a recursive function does not have a base case?',
    options: ['Stack overflow / infinite recursion', 'Returns 0', 'Returns null', 'Compilation error'],
    correctAnswer: 'Stack overflow / infinite recursion',
    explanation: 'Without a base case, the function calls itself indefinitely, consuming stack memory until a stack overflow occurs.',
    tags: ['recursion', 'base-case'],
  },

  // ===================== DSA - Dynamic Programming =====================
  {
    title: 'Fibonacci - DP vs Recursion',
    category: 'dsa',
    subject: 'Dynamic Programming',
    topic: 'Dynamic Programming',
    difficulty: 'medium',
    type: 'mcq',
    question: 'What is the time complexity of computing Fibonacci using memoization (top-down DP)?',
    options: ['O(n)', 'O(2^n)', 'O(n²)', 'O(n log n)'],
    correctAnswer: 'O(n)',
    explanation: 'Memoization stores previously computed results, so each Fibonacci number is computed only once. Time: O(n), Space: O(n).',
    tags: ['fibonacci', 'memoization', 'dp'],
  },
  {
    title: 'Longest Common Subsequence',
    category: 'dsa',
    subject: 'Dynamic Programming',
    topic: 'Dynamic Programming',
    difficulty: 'hard',
    type: 'mcq',
    question: 'What is the time complexity of the Longest Common Subsequence (LCS) problem using DP?',
    options: ['O(m × n)', 'O(m + n)', 'O(2^n)', 'O(n²)'],
    correctAnswer: 'O(m × n)',
    explanation: 'LCS uses a 2D DP table of size m×n (lengths of two strings), filling each cell in O(1). Total: O(m × n).',
    tags: ['lcs', 'dp', 'strings'],
  },

  // ===================== DSA - Sorting =====================
  {
    title: 'Quick Sort Average Complexity',
    category: 'dsa',
    subject: 'Sorting',
    topic: 'Sorting',
    difficulty: 'medium',
    type: 'mcq',
    question: 'What is the average time complexity of Quick Sort?',
    options: ['O(n log n)', 'O(n²)', 'O(n)', 'O(log n)'],
    correctAnswer: 'O(n log n)',
    explanation: 'Quick Sort has O(n log n) average case. Worst case is O(n²) when the pivot is always the smallest/largest element.',
    tags: ['quick-sort', 'sorting', 'complexity'],
  },
  {
    title: 'Stable Sorting Algorithm',
    category: 'dsa',
    subject: 'Sorting',
    topic: 'Sorting',
    difficulty: 'easy',
    type: 'mcq',
    question: 'Which of the following is a stable sorting algorithm?',
    options: ['Merge Sort', 'Quick Sort', 'Heap Sort', 'Selection Sort'],
    correctAnswer: 'Merge Sort',
    explanation: 'Merge Sort is stable — equal elements maintain their relative order. Quick Sort and Heap Sort are not stable by default.',
    tags: ['merge-sort', 'stable', 'sorting'],
  },

  // ===================== DSA - Searching =====================
  {
    title: 'Binary Search Prerequisite',
    category: 'dsa',
    subject: 'Searching',
    topic: 'Searching',
    difficulty: 'easy',
    type: 'mcq',
    question: 'What is the prerequisite for binary search?',
    options: ['Array must be sorted', 'Array must be unsorted', 'Array must have unique elements', 'Array size must be even'],
    correctAnswer: 'Array must be sorted',
    explanation: 'Binary search requires the array to be sorted. It repeatedly divides the search interval in half.',
    tags: ['binary-search', 'searching'],
  },

  // ===================== CODING - Problems =====================
  {
    title: 'Reverse a String',
    category: 'coding',
    subject: 'Strings',
    topic: 'String Manipulation',
    difficulty: 'easy',
    type: 'coding',
    question: 'Write a function to reverse a given string without using built-in reverse methods.',
    correctAnswer: 'function reverseString(str) {\n  let reversed = "";\n  for (let i = str.length - 1; i >= 0; i--) {\n    reversed += str[i];\n  }\n  return reversed;\n}',
    explanation: 'Iterate from the end of the string to the beginning, building a new string character by character.',
    constraints: '1 <= str.length <= 10^5',
    sampleInput: '"hello"',
    sampleOutput: '"olleh"',
    hints: ['Start from the last character and move backwards', 'You can also use two-pointer swap technique'],
    solution: 'function reverseString(str) {\n  let reversed = "";\n  for (let i = str.length - 1; i >= 0; i--) {\n    reversed += str[i];\n  }\n  return reversed;\n}\n\n// Alternative: Two-pointer approach\nfunction reverseString2(str) {\n  const arr = str.split("");\n  let left = 0, right = arr.length - 1;\n  while (left < right) {\n    [arr[left], arr[right]] = [arr[right], arr[left]];\n    left++;\n    right--;\n  }\n  return arr.join("");\n}',
    tags: ['string', 'reverse', 'easy'],
  },
  {
    title: 'FizzBuzz',
    category: 'coding',
    subject: 'Logic',
    topic: 'Basic Logic',
    difficulty: 'easy',
    type: 'coding',
    question: 'Write a function that returns an array of strings from 1 to n. For multiples of 3, use "Fizz", for multiples of 5, use "Buzz", for multiples of both, use "FizzBuzz".',
    correctAnswer: 'function fizzBuzz(n) {\n  const result = [];\n  for (let i = 1; i <= n; i++) {\n    if (i % 15 === 0) result.push("FizzBuzz");\n    else if (i % 3 === 0) result.push("Fizz");\n    else if (i % 5 === 0) result.push("Buzz");\n    else result.push(String(i));\n  }\n  return result;\n}',
    explanation: 'Check divisibility by 15 first (both 3 and 5), then by 3, then by 5. Otherwise, push the number as string.',
    constraints: '1 <= n <= 10^4',
    sampleInput: '15',
    sampleOutput: '["1","2","Fizz","4","Buzz","Fizz","7","8","Fizz","Buzz","11","Fizz","13","14","FizzBuzz"]',
    hints: ['Check for divisibility by 15 (3×5) first to handle the "FizzBuzz" case'],
    solution: 'function fizzBuzz(n) {\n  const result = [];\n  for (let i = 1; i <= n; i++) {\n    if (i % 15 === 0) result.push("FizzBuzz");\n    else if (i % 3 === 0) result.push("Fizz");\n    else if (i % 5 === 0) result.push("Buzz");\n    else result.push(String(i));\n  }\n  return result;\n}',
    tags: ['fizzbuzz', 'logic', 'easy'],
  },
  {
    title: 'Find Missing Number',
    category: 'coding',
    subject: 'Arrays',
    topic: 'Array Manipulation',
    difficulty: 'easy',
    type: 'coding',
    question: 'Given an array containing n distinct numbers from 0 to n, find the one number missing from the array.',
    correctAnswer: 'function missingNumber(nums) {\n  const n = nums.length;\n  const expectedSum = (n * (n + 1)) / 2;\n  const actualSum = nums.reduce((sum, num) => sum + num, 0);\n  return expectedSum - actualSum;\n}',
    explanation: 'Use the mathematical formula for sum of 0 to n, then subtract the actual sum to find the missing number.',
    constraints: '1 <= nums.length <= 10^4\n0 <= nums[i] <= n\nAll numbers are unique',
    sampleInput: '[3, 0, 1]',
    sampleOutput: '2',
    hints: ['Sum formula: n*(n+1)/2', 'XOR approach also works'],
    solution: 'function missingNumber(nums) {\n  const n = nums.length;\n  const expectedSum = (n * (n + 1)) / 2;\n  const actualSum = nums.reduce((sum, num) => sum + num, 0);\n  return expectedSum - actualSum;\n}\n\n// Alternative: XOR approach\nfunction missingNumberXOR(nums) {\n  let xor = nums.length;\n  for (let i = 0; i < nums.length; i++) {\n    xor ^= i ^ nums[i];\n  }\n  return xor;\n}',
    tags: ['arrays', 'math', 'missing-number'],
  },
  {
    title: 'Valid Anagram',
    category: 'coding',
    subject: 'Strings',
    topic: 'String Manipulation',
    difficulty: 'easy',
    type: 'coding',
    question: 'Given two strings s and t, return true if t is an anagram of s, and false otherwise.',
    correctAnswer: 'function isAnagram(s, t) {\n  if (s.length !== t.length) return false;\n  const charCount = {};\n  for (const char of s) charCount[char] = (charCount[char] || 0) + 1;\n  for (const char of t) {\n    if (!charCount[char]) return false;\n    charCount[char]--;\n  }\n  return true;\n}',
    explanation: 'Count character frequencies in the first string, then decrement for the second. If all counts reach 0, it\'s an anagram.',
    constraints: '1 <= s.length, t.length <= 5 * 10^4\ns and t consist of lowercase English letters',
    sampleInput: 's = "anagram", t = "nagaram"',
    sampleOutput: 'true',
    hints: ['Use a hash map to count character frequencies', 'Sorting both strings also works but is O(n log n)'],
    solution: 'function isAnagram(s, t) {\n  if (s.length !== t.length) return false;\n  const charCount = {};\n  for (const char of s) charCount[char] = (charCount[char] || 0) + 1;\n  for (const char of t) {\n    if (!charCount[char]) return false;\n    charCount[char]--;\n  }\n  return true;\n}',
    tags: ['anagram', 'hash-map', 'strings'],
  },
  {
    title: 'Palindrome Number',
    category: 'coding',
    subject: 'Math',
    topic: 'Number Manipulation',
    difficulty: 'easy',
    type: 'coding',
    question: 'Given an integer x, return true if x is a palindrome, and false otherwise, without converting to a string.',
    correctAnswer: 'function isPalindrome(x) {\n  if (x < 0) return false;\n  let original = x, reversed = 0;\n  while (x > 0) {\n    reversed = reversed * 10 + (x % 10);\n    x = Math.floor(x / 10);\n  }\n  return original === reversed;\n}',
    explanation: 'Reverse the number mathematically by extracting digits from the end. Compare the reversed number with the original.',
    constraints: '-2^31 <= x <= 2^31 - 1',
    sampleInput: '121',
    sampleOutput: 'true',
    hints: ['Negative numbers are not palindromes', 'Extract digits using modulo and division'],
    solution: 'function isPalindrome(x) {\n  if (x < 0) return false;\n  let original = x, reversed = 0;\n  while (x > 0) {\n    reversed = reversed * 10 + (x % 10);\n    x = Math.floor(x / 10);\n  }\n  return original === reversed;\n}',
    tags: ['palindrome', 'math', 'number'],
  },

  // ===================== HR Questions =====================
  {
    title: 'Tell Me About Yourself',
    category: 'hr',
    subject: 'HR',
    topic: 'Introduction',
    difficulty: 'easy',
    type: 'subjective',
    question: 'Tell me about yourself.',
    correctAnswer: 'Structure your answer with: 1) Brief intro (name, education), 2) Relevant skills and experience, 3) Why you\'re interested in this role, 4) A closing statement about what you bring to the table.',
    explanation: 'Keep it professional, concise (2-3 minutes), and relevant to the role. Avoid personal details unrelated to work.',
    tags: ['hr', 'introduction'],
  },
  {
    title: 'Strengths and Weaknesses',
    category: 'hr',
    subject: 'HR',
    topic: 'Self Assessment',
    difficulty: 'medium',
    type: 'subjective',
    question: 'What are your strengths and weaknesses?',
    correctAnswer: 'For strengths: Pick 2-3 strengths relevant to the job with specific examples. For weaknesses: Choose a genuine weakness you\'re actively working to improve. Show self-awareness and growth mindset.',
    explanation: 'Be authentic. Avoid cliché answers like "I\'m a perfectionist." Give real examples and show how you manage your weakness.',
    tags: ['hr', 'self-assessment'],
  },
  {
    title: 'Why Should We Hire You?',
    category: 'hr',
    subject: 'HR',
    topic: 'Motivation',
    difficulty: 'medium',
    type: 'subjective',
    question: 'Why should we hire you?',
    correctAnswer: 'Align your skills, experience, and enthusiasm with the role requirements. Highlight unique qualities and how you can add value to the team.',
    explanation: 'Research the company and role. Connect your qualifications to their needs. Show enthusiasm and cultural fit.',
    tags: ['hr', 'motivation'],
  },
  {
    title: 'Where Do You See Yourself in 5 Years?',
    category: 'hr',
    subject: 'HR',
    topic: 'Career Goals',
    difficulty: 'easy',
    type: 'subjective',
    question: 'Where do you see yourself in 5 years?',
    correctAnswer: 'Show ambition aligned with the company\'s growth. Mention skill development, taking on more responsibilities, and contributing to the organization\'s goals.',
    explanation: 'Avoid being too specific or vague. Show commitment to the company while demonstrating growth mindset.',
    tags: ['hr', 'career-goals'],
  },
  {
    title: 'Handle Conflict at Work',
    category: 'hr',
    subject: 'HR',
    topic: 'Conflict Resolution',
    difficulty: 'medium',
    type: 'subjective',
    question: 'How do you handle conflicts at work?',
    correctAnswer: 'Use the STAR method: Describe a specific situation, the task at hand, the actions you took (active listening, finding common ground, professional communication), and the positive result.',
    explanation: 'Emphasize communication, empathy, and problem-solving skills. Show maturity in handling disagreements professionally.',
    tags: ['hr', 'conflict-resolution'],
  },

  // ===================== BEHAVIORAL Questions =====================
  {
    title: 'Describe a Challenging Project',
    category: 'behavioral',
    subject: 'Behavioral',
    topic: 'Problem Solving',
    difficulty: 'medium',
    type: 'subjective',
    question: 'Describe a challenging project you worked on and how you overcame the challenges.',
    correctAnswer: 'Use STAR method: Situation (what was the project), Task (what was your role), Action (specific steps you took to overcome challenges), Result (what was the outcome, what you learned).',
    explanation: 'Choose a project that demonstrates problem-solving, persistence, and growth. Quantify results where possible.',
    tags: ['behavioral', 'problem-solving'],
  },
  {
    title: 'Team Leadership Experience',
    category: 'behavioral',
    subject: 'Behavioral',
    topic: 'Leadership',
    difficulty: 'medium',
    type: 'subjective',
    question: 'Tell me about a time you led a team or took initiative.',
    correctAnswer: 'Describe the situation, your leadership actions (delegating, motivating, resolving conflicts), and the team\'s achievement. Highlight communication and decision-making skills.',
    explanation: 'Focus on how you influenced the team positively. Show emotional intelligence and results-oriented leadership.',
    tags: ['behavioral', 'leadership'],
  },
  {
    title: 'Learning from Failure',
    category: 'behavioral',
    subject: 'Behavioral',
    topic: 'Self Improvement',
    difficulty: 'medium',
    type: 'subjective',
    question: 'Tell me about a time you failed and what you learned from it.',
    correctAnswer: 'Be honest about a real failure. Explain what went wrong, take responsibility, describe what you learned, and how you applied that lesson going forward.',
    explanation: 'Showing vulnerability and growth mindset is valued. Focus more on the learning and improvement than the failure itself.',
    tags: ['behavioral', 'failure', 'learning'],
  },
  {
    title: 'Working Under Pressure',
    category: 'behavioral',
    subject: 'Behavioral',
    topic: 'Stress Management',
    difficulty: 'easy',
    type: 'subjective',
    question: 'How do you handle working under pressure or tight deadlines?',
    correctAnswer: 'Describe your prioritization techniques, time management strategies, and stress coping mechanisms. Give a specific example where you delivered quality work under pressure.',
    explanation: 'Show that you can remain calm, prioritize effectively, and still deliver quality work when the pressure is on.',
    tags: ['behavioral', 'pressure', 'stress'],
  },
  {
    title: 'Adaptability to Change',
    category: 'behavioral',
    subject: 'Behavioral',
    topic: 'Adaptability',
    difficulty: 'easy',
    type: 'subjective',
    question: 'Describe a situation where you had to adapt to a significant change.',
    correctAnswer: 'Share a specific example of unexpected change (new technology, role change, process change). Explain how you embraced it, learned quickly, and achieved positive outcomes.',
    explanation: 'Demonstrate flexibility, positive attitude towards change, and ability to learn quickly in new environments.',
    tags: ['behavioral', 'adaptability', 'change'],
  },
];

const seedDB = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('✅ Connected to MongoDB');

    // Clear existing data
    await Question.deleteMany({});
    console.log('🗑️  Cleared existing questions');

    // Insert questions
    const insertedQuestions = await Question.insertMany(questions);
    console.log(`✅ Inserted ${insertedQuestions.length} questions`);

    // Create a demo admin user
    const existingAdmin = await User.findOne({ email: 'admin@placementpro.com' });
    if (!existingAdmin) {
      await User.create({
        name: 'Admin User',
        email: 'admin@placementpro.com',
        password: 'admin123456',
        role: 'admin',
        college: 'PlacementPro University',
        branch: 'Computer Science',
        graduationYear: 2025,
        badges: ['newcomer', 'admin'],
        achievements: ['Registered on PlacementPro', 'Admin privileges granted'],
      });
      console.log('✅ Created admin user (admin@placementpro.com / admin123456)');
    }

    // Create a demo regular user
    const existingUser = await User.findOne({ email: 'demo@placementpro.com' });
    if (!existingUser) {
      await User.create({
        name: 'Demo Student',
        email: 'demo@placementpro.com',
        password: 'demo123456',
        college: 'IIT Delhi',
        branch: 'Computer Science',
        graduationYear: 2025,
        badges: ['newcomer'],
        achievements: ['Registered on PlacementPro'],
      });
      console.log('✅ Created demo user (demo@placementpro.com / demo123456)');
    }

    console.log('\n🎉 Database seeded successfully!');
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    console.log('Admin: admin@placementpro.com / admin123456');
    console.log('Demo:  demo@placementpro.com / demo123456');
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');

    process.exit(0);
  } catch (error) {
    console.error('❌ Seeding error:', error.message);
    process.exit(1);
  }
};

seedDB();
