import dns from 'dns';
import mongoose from 'mongoose';
import dotenv from 'dotenv';
import Question from './models/Question.js';
import User from './models/User.js';

try {
  dns.setServers(['8.8.8.8', '1.1.1.1']);
} catch (e) {}

dotenv.config();

const questions = [
  // =========================================================================
  // ===================== SECTION 1: APTITUDE (30 Questions) ================
  // =========================================================================
  
  // ----- Quantitative Aptitude - Easy -----
  {
    title: 'Profit and Loss Percentage',
    category: 'aptitude',
    subject: 'Quantitative Aptitude',
    topic: 'Profit and Loss',
    difficulty: 'easy',
    type: 'mcq',
    question: 'A shopkeeper buys an article for ₹500 and sells it for ₹600. What is the profit percentage?',
    options: ['15%', '20%', '25%', '10%'],
    correctAnswer: '20%',
    explanation: 'Profit = 600 - 500 = ₹100. Profit% = (100/500) × 100 = 20%.',
    tags: ['profit-loss', 'percentage', 'arithmetic'],
  },
  {
    title: 'Simple Interest Calculation',
    category: 'aptitude',
    subject: 'Quantitative Aptitude',
    topic: 'Simple Interest',
    difficulty: 'easy',
    type: 'mcq',
    question: 'Find the simple interest on ₹5000 at 8% per annum for 3 years.',
    options: ['₹1200', '₹1000', '₹800', '₹1500'],
    correctAnswer: '₹1200',
    explanation: 'SI = P × R × T / 100 = 5000 × 8 × 3 / 100 = ₹1200.',
    tags: ['simple-interest', 'arithmetic'],
  },
  {
    title: 'Average of Consecutive Numbers',
    category: 'aptitude',
    subject: 'Quantitative Aptitude',
    topic: 'Averages',
    difficulty: 'easy',
    type: 'mcq',
    question: 'The average of 5 consecutive odd numbers starting from 3 is:',
    options: ['5', '7', '9', '11'],
    correctAnswer: '7',
    explanation: 'The numbers are 3, 5, 7, 9, 11. Average = (3+5+7+9+11)/5 = 35/5 = 7.',
    tags: ['averages', 'arithmetic'],
  },
  {
    title: 'Ratio and Proportion Basic',
    category: 'aptitude',
    subject: 'Quantitative Aptitude',
    topic: 'Ratio and Proportion',
    difficulty: 'easy',
    type: 'mcq',
    question: 'If A:B = 3:4 and B:C = 5:6, then A:B:C is:',
    options: ['15:20:24', '3:4:6', '9:12:16', '15:20:18'],
    correctAnswer: '15:20:24',
    explanation: 'A:B = 3:4 = 15:20 and B:C = 5:6 = 20:24. Therefore A:B:C = 15:20:24.',
    tags: ['ratio', 'proportion'],
  },
  {
    title: 'Percentage Net Change',
    category: 'aptitude',
    subject: 'Quantitative Aptitude',
    topic: 'Percentages',
    difficulty: 'easy',
    type: 'mcq',
    question: 'If a number is increased by 25% and the resulting number is then decreased by 20%, the overall percentage change is:',
    options: ['0%', '5% increase', '5% decrease', '10% increase'],
    correctAnswer: '0%',
    explanation: 'Let x be the number. After 25% increase: 1.25x. After 20% decrease: 1.25x × 0.8 = x. Net change = 0%.',
    tags: ['percentages', 'arithmetic'],
  },
  {
    title: 'Simplification of Powers',
    category: 'aptitude',
    subject: 'Quantitative Aptitude',
    topic: 'Number System',
    difficulty: 'easy',
    type: 'mcq',
    question: 'What is the unit digit of 3^65?',
    options: ['3', '9', '7', '1'],
    correctAnswer: '3',
    explanation: 'Cyclicity of 3 is 4 (3, 9, 7, 1). 65 mod 4 = 1. So unit digit is 3^1 = 3.',
    tags: ['number-system', 'cyclicity'],
  },

  // ----- Quantitative Aptitude - Medium -----
  {
    title: 'Time and Work Problem',
    category: 'aptitude',
    subject: 'Quantitative Aptitude',
    topic: 'Time and Work',
    difficulty: 'medium',
    type: 'mcq',
    question: 'A can do a work in 15 days and B can do it in 20 days. If they work together for 4 days, what fraction of work is left?',
    options: ['8/15', '7/15', '11/15', '1/5'],
    correctAnswer: '8/15',
    explanation: '1 day work = 1/15 + 1/20 = 7/60. In 4 days, work done = 4 × 7/60 = 7/15. Work left = 1 - 7/15 = 8/15.',
    tags: ['time-work', 'fractions'],
  },
  {
    title: 'Speed Distance and Trains',
    category: 'aptitude',
    subject: 'Quantitative Aptitude',
    topic: 'Speed Distance Time',
    difficulty: 'medium',
    type: 'mcq',
    question: 'A train 200m long crosses a platform 300m long in 25 seconds. What is the speed of the train in km/hr?',
    options: ['72 km/hr', '60 km/hr', '80 km/hr', '54 km/hr'],
    correctAnswer: '72 km/hr',
    explanation: 'Total distance = 200 + 300 = 500m. Speed = 500/25 = 20 m/s = 20 × 18/5 = 72 km/hr.',
    tags: ['speed', 'distance', 'trains'],
  },
  {
    title: 'Pipes and Cisterns',
    category: 'aptitude',
    subject: 'Quantitative Aptitude',
    topic: 'Pipes and Cisterns',
    difficulty: 'medium',
    type: 'mcq',
    question: 'Two pipes A and B can fill a tank in 20 minutes and 30 minutes respectively. If both are opened together, how long will it take to fill the tank?',
    options: ['12 minutes', '15 minutes', '25 minutes', '10 minutes'],
    correctAnswer: '12 minutes',
    explanation: 'Combined rate = 1/20 + 1/30 = 5/60 = 1/12 per minute. Time = 12 minutes.',
    tags: ['pipes', 'work'],
  },
  {
    title: 'Probability of Cards',
    category: 'aptitude',
    subject: 'Quantitative Aptitude',
    topic: 'Probability',
    difficulty: 'medium',
    type: 'mcq',
    question: 'Two cards are drawn at random from a standard deck of 52 cards. What is the probability that both are aces?',
    options: ['1/221', '1/169', '1/13', '1/26'],
    correctAnswer: '1/221',
    explanation: 'P(1st Ace) = 4/52 = 1/13. P(2nd Ace) = 3/51 = 1/17. Combined P = (1/13) × (1/17) = 1/221.',
    tags: ['probability', 'cards'],
  },

  // ----- Quantitative Aptitude - Hard -----
  {
    title: 'Compound Interest Annual vs Semi-Annual',
    category: 'aptitude',
    subject: 'Quantitative Aptitude',
    topic: 'Compound Interest',
    difficulty: 'hard',
    type: 'mcq',
    question: 'Find the difference between compound interest compounded annually and semi-annually on ₹10,000 for 1.5 years at 10% per annum.',
    options: ['₹76.25', '₹80.50', '₹50.00', '₹100.25'],
    correctAnswer: '₹76.25',
    explanation: 'CI Annually = 10000(1 + 0.1)^1 * (1 + 0.05) - 10000 = ₹1550. CI Semi-annually = 10000(1 + 0.05)^3 - 10000 = ₹1576.25. Difference = 1576.25 - 1500 - 50 = ₹76.25.',
    tags: ['compound-interest', 'hard-arithmetic'],
  },
  {
    title: 'Permutations & Combinations Seating Arrangement',
    category: 'aptitude',
    subject: 'Quantitative Aptitude',
    topic: 'Permutations & Combinations',
    difficulty: 'hard',
    type: 'mcq',
    question: 'In how many ways can 5 men and 4 women be seated in a row such that no two women sit together?',
    options: ['43,200', '14,400', '28,800', '57,600'],
    correctAnswer: '43,200',
    explanation: '5 men can be arranged in 5! = 120 ways. This creates 6 gaps. 4 women choose 4 gaps out of 6 in 6P4 = 360 ways. Total = 120 × 360 = 43,200 ways.',
    tags: ['permutations', 'combinations'],
  },

  // ----- Logical Reasoning - Easy -----
  {
    title: 'Number Series Pattern',
    category: 'aptitude',
    subject: 'Logical Reasoning',
    topic: 'Number Series',
    difficulty: 'easy',
    type: 'mcq',
    question: 'What comes next in the series: 2, 6, 12, 20, 30, ?',
    options: ['42', '40', '38', '44'],
    correctAnswer: '42',
    explanation: 'Differences: +4, +6, +8, +10, +12. The next number is 30 + 12 = 42.',
    tags: ['number-series', 'pattern'],
  },
  {
    title: 'Direction Sense Test',
    category: 'aptitude',
    subject: 'Logical Reasoning',
    topic: 'Direction Sense',
    difficulty: 'easy',
    type: 'mcq',
    question: 'Ravi walks 10m North, turns right and walks 15m, then turns right again and walks 10m. In which direction is he facing now?',
    options: ['South', 'East', 'West', 'North'],
    correctAnswer: 'South',
    explanation: 'North → Right (East) → Right (South). He faces South.',
    tags: ['direction', 'reasoning'],
  },
  {
    title: 'Alphabet Analogy',
    category: 'aptitude',
    subject: 'Logical Reasoning',
    topic: 'Analogy',
    difficulty: 'easy',
    type: 'mcq',
    question: 'If CAT is coded as 3120, then DOG is coded as:',
    options: ['4157', '4147', '3157', '4158'],
    correctAnswer: '4157',
    explanation: 'Letters correspond to positional numbers: C=3, A=1, T=20. D=4, O=15, G=7 → 4157.',
    tags: ['analogy', 'coding'],
  },

  // ----- Logical Reasoning - Medium -----
  {
    title: 'Blood Relations Puzzle',
    category: 'aptitude',
    subject: 'Logical Reasoning',
    topic: 'Blood Relations',
    difficulty: 'medium',
    type: 'mcq',
    question: 'Pointing to a man, a woman said, "His mother is the only daughter of my mother." How is the woman related to the man?',
    options: ['Mother', 'Grandmother', 'Sister', 'Aunt'],
    correctAnswer: 'Mother',
    explanation: 'The only daughter of my mother = the woman herself. So the man\'s mother is the woman.',
    tags: ['blood-relations', 'reasoning'],
  },
  {
    title: 'Coding-Decoding Pattern',
    category: 'aptitude',
    subject: 'Logical Reasoning',
    topic: 'Coding-Decoding',
    difficulty: 'medium',
    type: 'mcq',
    question: 'If COMPUTER is coded as RFUVQNPD, how is MEDICINE coded?',
    options: ['FNDJDJEM', 'EDJDJEFN', 'FOJEJEFN', 'FNJEDJEM'],
    correctAnswer: 'FNDJDJEM',
    explanation: 'Reversed order + 1 shift per letter. MEDICINE reversed is ENIDICEM → +1 → FNDJDJEM.',
    tags: ['coding-decoding', 'reasoning'],
  },
  {
    title: 'Seating Arrangement Circular',
    category: 'aptitude',
    subject: 'Logical Reasoning',
    topic: 'Seating Arrangement',
    difficulty: 'medium',
    type: 'mcq',
    question: 'A, B, C, D, E sit in a circle facing the center. A is right of B, E is left of B, C is right of A. Who sits to the immediate left of E?',
    options: ['D', 'C', 'A', 'B'],
    correctAnswer: 'D',
    explanation: 'Order clockwise: B, A, C, D, E. To the immediate left of E is D.',
    tags: ['seating-arrangement', 'logic'],
  },

  // ----- Logical Reasoning - Hard -----
  {
    title: 'Syllogism Complex Deduction',
    category: 'aptitude',
    subject: 'Logical Reasoning',
    topic: 'Syllogisms',
    difficulty: 'hard',
    type: 'mcq',
    question: 'Statements: All dogs are animals. No animal is a reptile. Some reptiles are frogs.\nConclusions:\nI. No dog is a reptile.\nII. Some frogs are animals.',
    options: ['Only I follows', 'Only II follows', 'Both follow', 'Neither follows'],
    correctAnswer: 'Only I follows',
    explanation: 'Since all dogs are animals and no animal is a reptile, no dog can be a reptile (I follows). Frogs and animals do not necessarily overlap (II does not follow).',
    tags: ['syllogism', 'logic'],
  },
  {
    title: 'Data Sufficiency Clock Angles',
    category: 'aptitude',
    subject: 'Logical Reasoning',
    topic: 'Clocks',
    difficulty: 'hard',
    type: 'mcq',
    question: 'At what time between 3 o\'clock and 4 o\'clock will the hands of a clock be together?',
    options: ['3:16 4/11 min', '3:15 min', '3:18 2/11 min', '3:20 min'],
    correctAnswer: '3:16 4/11 min',
    explanation: 'At 3:00, gap is 15 minute spaces. Speed difference = 55 min spaces in 60 min = 11/12 min space/min. Time = 15 × (12/11) = 180/11 = 16 4/11 minutes past 3.',
    tags: ['clocks', 'angles'],
  },

  // ----- Verbal Ability - Easy -----
  {
    title: 'Synonym of Eloquent',
    category: 'aptitude',
    subject: 'Verbal Ability',
    topic: 'Synonyms',
    difficulty: 'easy',
    type: 'mcq',
    question: 'Choose the synonym of "Eloquent":',
    options: ['Articulate', 'Silent', 'Rude', 'Modest'],
    correctAnswer: 'Articulate',
    explanation: 'Eloquent means fluent and persuasive in speaking or writing. Articulate has a similar meaning.',
    tags: ['synonyms', 'vocabulary'],
  },
  {
    title: 'Antonym of Benevolent',
    category: 'aptitude',
    subject: 'Verbal Ability',
    topic: 'Antonyms',
    difficulty: 'easy',
    type: 'mcq',
    question: 'Choose the antonym of "Benevolent":',
    options: ['Malevolent', 'Kind', 'Generous', 'Friendly'],
    correctAnswer: 'Malevolent',
    explanation: 'Benevolent means well-meaning and kindly. Malevolent means having ill will, the opposite.',
    tags: ['antonyms', 'vocabulary'],
  },
  {
    title: 'Fill in the Blanks Preposition',
    category: 'aptitude',
    subject: 'Verbal Ability',
    topic: 'Grammar',
    difficulty: 'easy',
    type: 'mcq',
    question: 'He has been living in this city _____ 2015.',
    options: ['since', 'for', 'from', 'by'],
    correctAnswer: 'since',
    explanation: '"Since" is used for a specific point in time in perfect tenses (since 2015).',
    tags: ['grammar', 'prepositions'],
  },

  // ----- Verbal Ability - Medium -----
  {
    title: 'Subject-Verb Agreement',
    category: 'aptitude',
    subject: 'Verbal Ability',
    topic: 'Grammar',
    difficulty: 'medium',
    type: 'mcq',
    question: 'Choose the grammatically correct sentence:',
    options: [
      'Neither the students nor the teacher was present.',
      'Neither the students nor the teacher were present.',
      'Neither the students or the teacher was present.',
      'Neither the students or the teacher were present.',
    ],
    correctAnswer: 'Neither the students nor the teacher was present.',
    explanation: 'With "neither...nor", the verb agrees with the subject closest to it ("teacher" is singular → "was").',
    tags: ['grammar', 'subject-verb'],
  },
  {
    title: 'Idiom Meaning',
    category: 'aptitude',
    subject: 'Verbal Ability',
    topic: 'Idioms',
    difficulty: 'medium',
    type: 'mcq',
    question: 'What is the meaning of the idiom "To bite the bullet"?',
    options: [
      'To face a difficult situation with courage',
      'To get injured in a battle',
      'To eat quickly',
      'To compromise on principles',
    ],
    correctAnswer: 'To face a difficult situation with courage',
    explanation: 'Bite the bullet means to endure a painful or difficult situation that is unavoidable.',
    tags: ['idioms', 'verbal'],
  },
  {
    title: 'Reading Comprehension Main Idea',
    category: 'aptitude',
    subject: 'Verbal Ability',
    topic: 'Reading Comprehension',
    difficulty: 'medium',
    type: 'mcq',
    question: 'Passage: "Artificial Intelligence is transforming global healthcare. Machine learning models diagnose diseases with unprecedented speed, though data privacy concerns linger." What is the author\'s main tone?',
    options: ['Balanced and analytical', 'Overly pessimistic', 'purely aggressive', 'Indifferent'],
    correctAnswer: 'Balanced and analytical',
    explanation: 'The passage highlights both benefits (speed/diagnosis) and concerns (privacy), demonstrating a balanced analytical tone.',
    tags: ['comprehension', 'tone'],
  },

  // ----- Verbal Ability - Hard -----
  {
    title: 'Sentence Rearrangement (Para Jumbles)',
    category: 'aptitude',
    subject: 'Verbal Ability',
    topic: 'Para Jumbles',
    difficulty: 'hard',
    type: 'mcq',
    question: 'Arrange in logical order:\nP: Renewable energy capacity grew by 10% last year.\nQ: Solar and wind power led this surge.\nR: Global energy transitions are accelerating.\nS: However, grid storage remains a major bottleneck.',
    options: ['R, P, Q, S', 'P, Q, R, S', 'R, S, P, Q', 'S, R, P, Q'],
    correctAnswer: 'R, P, Q, S',
    explanation: 'R states the general thesis (transitions accelerating). P gives data (10% growth). Q elaborates on sources (solar/wind). S provides contrast (storage bottleneck).',
    tags: ['para-jumbles', 'verbal'],
  },

  // =========================================================================
  // ===================== SECTION 2: TECHNICAL (30 Questions) ================
  // =========================================================================
  
  // ----- JavaScript - Easy / Medium / Hard -----
  {
    title: 'JavaScript Closures Execution',
    category: 'technical',
    subject: 'JavaScript',
    topic: 'Closures',
    difficulty: 'medium',
    type: 'mcq',
    question: 'What is the output?\nfunction outer() {\n  let count = 0;\n  return function() { return ++count; };\n}\nconst fn = outer();\nconsole.log(fn(), fn(), fn());',
    options: ['1 2 3', '1 1 1', '0 1 2', 'undefined'],
    correctAnswer: '1 2 3',
    explanation: 'The returned inner function maintains access to `count` via closure, incrementing it on each call.',
    tags: ['javascript', 'closures'],
  },
  {
    title: 'Event Loop & Async Microtasks',
    category: 'technical',
    subject: 'JavaScript',
    topic: 'Event Loop',
    difficulty: 'medium',
    type: 'mcq',
    question: 'What prints first?\nconsole.log("A");\nsetTimeout(() => console.log("B"), 0);\nPromise.resolve().then(() => console.log("C"));\nconsole.log("D");',
    options: ['A D C B', 'A B C D', 'A D B C', 'A C D B'],
    correctAnswer: 'A D C B',
    explanation: 'Synchronous execution: A, D. Microtask queue (Promise): C. Macrotask queue (setTimeout): B.',
    tags: ['javascript', 'event-loop', 'async'],
  },
  {
    title: 'Var vs Let Hoisting',
    category: 'technical',
    subject: 'JavaScript',
    topic: 'Variables',
    difficulty: 'easy',
    type: 'mcq',
    question: 'What happens when accessing a "let" variable before its declaration?',
    options: ['ReferenceError (TDZ)', 'undefined', 'null', 'SyntaxError'],
    correctAnswer: 'ReferenceError (TDZ)',
    explanation: 'Variables declared with let/const are in the Temporal Dead Zone (TDZ) from block start to declaration, throwing ReferenceError.',
    tags: ['javascript', 'hoisting', 'tdz'],
  },
  {
    title: 'JS Prototypal Inheritance',
    category: 'technical',
    subject: 'JavaScript',
    topic: 'Prototypes',
    difficulty: 'hard',
    type: 'mcq',
    question: 'What does Object.create(proto) do in JavaScript?',
    options: [
      'Creates a new object with its internal [[Prototype]] set to proto',
      'Copies all properties of proto into a new object',
      'Creates a deep clone of proto',
      'Extends proto in the global window object',
    ],
    correctAnswer: 'Creates a new object with its internal [[Prototype]] set to proto',
    explanation: 'Object.create() creates a new object using an existing object as the prototype of the newly created object.',
    tags: ['javascript', 'prototypes', 'oop'],
  },

  // ----- Python - Easy / Medium / Hard -----
  {
    title: 'Python List Comprehension Output',
    category: 'technical',
    subject: 'Python',
    topic: 'List Comprehension',
    difficulty: 'easy',
    type: 'mcq',
    question: 'What is the output of: [x**2 for x in range(5) if x % 2 == 0]?',
    options: ['[0, 4, 16]', '[1, 9, 25]', '[0, 2, 4]', '[0, 1, 4, 9, 16]'],
    correctAnswer: '[0, 4, 16]',
    explanation: 'range(5) gives 0,1,2,3,4. Even numbers are 0,2,4. Squared: 0^2=0, 2^2=4, 4^2=16.',
    tags: ['python', 'list-comprehension'],
  },
  {
    title: 'Python Global Interpreter Lock (GIL)',
    category: 'technical',
    subject: 'Python',
    topic: 'Concurrency',
    difficulty: 'hard',
    type: 'mcq',
    question: 'Why does GIL prevent true CPU-bound multithreading in CPython?',
    options: [
      'Because only one native thread can execute Python bytecode at a time',
      'Because Python does not support threads',
      'Because operating systems disable thread scheduling for Python',
      'Because memory is shared without lock',
    ],
    correctAnswer: 'Because only one native thread can execute Python bytecode at a time',
    explanation: 'The GIL is a mutex that protects access to Python objects, preventing multiple native threads from executing CPython bytecodes at once.',
    tags: ['python', 'gil', 'concurrency'],
  },
  {
    title: 'Python Mutable Default Arguments',
    category: 'technical',
    subject: 'Python',
    topic: 'Functions',
    difficulty: 'medium',
    type: 'mcq',
    question: 'What is the output?\ndef append_to(element, target=[]):\n    target.append(element)\n    return target\nprint(append_to(1))\nprint(append_to(2))',
    options: ['[1] then [1, 2]', '[1] then [2]', '[1, 2] then [1, 2]', 'Error'],
    correctAnswer: '[1] then [1, 2]',
    explanation: 'Default arguments in Python are evaluated once when the function is defined, so the same list is mutated across function calls.',
    tags: ['python', 'gotchas', 'functions'],
  },

  // ----- Java - Easy / Medium / Hard -----
  {
    title: 'Java String Pool & Memory',
    category: 'technical',
    subject: 'Java',
    topic: 'Memory Management',
    difficulty: 'medium',
    type: 'mcq',
    question: 'What is the output of: String s1 = "hello"; String s2 = new String("hello"); System.out.println(s1 == s2);',
    options: ['false', 'true', 'Compilation Error', 'NullPointerException'],
    correctAnswer: 'false',
    explanation: 's1 refers to the String Constant Pool instance, while s2 explicitly creates a new object on the Heap. The `==` operator compares reference memory addresses.',
    tags: ['java', 'strings', 'memory'],
  },
  {
    title: 'Java Interfaces Default Methods',
    category: 'technical',
    subject: 'Java',
    topic: 'Interfaces',
    difficulty: 'easy',
    type: 'mcq',
    question: 'Since Java 8, interface methods can have default implementations using which keyword?',
    options: ['default', 'static', 'abstract', 'final'],
    correctAnswer: 'default',
    explanation: 'Java 8 introduced default methods in interfaces to allow adding new methods without breaking implementing classes.',
    tags: ['java', 'java8', 'interfaces'],
  },
  {
    title: 'Java Concurrent HashMap Lock Granularity',
    category: 'technical',
    subject: 'Java',
    topic: 'Concurrency',
    difficulty: 'hard',
    type: 'mcq',
    question: 'How does ConcurrentHashMap achieve high concurrency in Java 8 compared to Hashtable?',
    options: [
      'Using CAS operations and synchronized bucket nodes instead of locking the entire table',
      'Using global read/write lock',
      'Disallowing null keys only',
      'Storing data on disk',
    ],
    correctAnswer: 'Using CAS operations and synchronized bucket nodes instead of locking the entire table',
    explanation: 'In Java 8, ConcurrentHashMap uses fine-grained locking (synchronized first node of a bucket) and CAS (Compare-And-Swap) operations instead of locking the whole table.',
    tags: ['java', 'concurrency', 'hashmap'],
  },

  // ----- DBMS & SQL - Easy / Medium / Hard -----
  {
    title: 'Database ACID Properties - Isolation Levels',
    category: 'technical',
    subject: 'DBMS',
    topic: 'Transactions',
    difficulty: 'hard',
    type: 'mcq',
    question: 'Which SQL isolation level prevents Phantom Reads?',
    options: ['SERIALIZABLE', 'READ COMMITTED', 'READ UNCOMMITTED', 'REPEATABLE READ'],
    correctAnswer: 'SERIALIZABLE',
    explanation: 'SERIALIZABLE is the highest isolation level. It prevents Dirty Reads, Non-repeatable Reads, and Phantom Reads.',
    tags: ['dbms', 'acid', 'isolation'],
  },
  {
    title: 'SQL Foreign Key Constraint',
    category: 'technical',
    subject: 'DBMS',
    topic: 'Constraints',
    difficulty: 'easy',
    type: 'mcq',
    question: 'What does a FOREIGN KEY constraint do?',
    options: [
      'Ensures referential integrity between two tables',
      'Uniquely identifies each row in a table',
      'Prevents null values in a column',
      'Indexes columns for fast search',
    ],
    correctAnswer: 'Ensures referential integrity between two tables',
    explanation: 'A FOREIGN KEY points to a PRIMARY KEY in another table to maintain referential integrity.',
    tags: ['sql', 'dbms', 'keys'],
  },
  {
    title: 'SQL Indexing B-Tree Mechanism',
    category: 'technical',
    subject: 'DBMS',
    topic: 'Indexing',
    difficulty: 'medium',
    type: 'mcq',
    question: 'What data structure is predominantly used for database indexing in relational DBMS like MySQL InnoDB?',
    options: ['B+ Tree', 'Binary Search Tree', 'Hash Table', 'Red-Black Tree'],
    correctAnswer: 'B+ Tree',
    explanation: 'B+ Trees store all data records in leaf nodes connected by a linked list, making range queries and disk block retrieval extremely fast.',
    tags: ['dbms', 'indexing', 'b-tree'],
  },
  {
    title: 'SQL HAVING vs WHERE',
    category: 'technical',
    subject: 'SQL',
    topic: 'Queries',
    difficulty: 'medium',
    type: 'mcq',
    question: 'What is the main difference between WHERE and HAVING clauses in SQL?',
    options: [
      'WHERE filters individual rows before grouping; HAVING filters aggregated groups',
      'HAVING filters rows before grouping; WHERE filters aggregated groups',
      'WHERE is for subqueries only',
      'HAVING is faster than WHERE',
    ],
    correctAnswer: 'WHERE filters individual rows before grouping; HAVING filters aggregated groups',
    explanation: 'WHERE filters rows before GROUP BY happens. HAVING filters aggregated data produced by GROUP BY.',
    tags: ['sql', 'where', 'having'],
  },

  // ----- Operating Systems - Easy / Medium / Hard -----
  {
    title: 'OS Process vs Thread Memory',
    category: 'technical',
    subject: 'Operating System',
    topic: 'Processes',
    difficulty: 'easy',
    type: 'mcq',
    question: 'Which memory component is unique to each thread in a multi-threaded process?',
    options: ['Stack and Registers', 'Heap', 'Global Variables', 'Code Segment'],
    correctAnswer: 'Stack and Registers',
    explanation: 'Threads share Heap, Code, and Data segments, but each thread has its own Stack pointer and Registers.',
    tags: ['os', 'threads', 'memory'],
  },
  {
    title: 'OS Deadlock Four Conditions',
    category: 'technical',
    subject: 'Operating System',
    topic: 'Deadlock',
    difficulty: 'medium',
    type: 'mcq',
    question: 'Which of the following is NOT one of Coffman\'s four necessary conditions for Deadlock?',
    options: ['Preemption', 'Mutual Exclusion', 'Hold and Wait', 'Circular Wait'],
    correctAnswer: 'Preemption',
    explanation: 'The 4 conditions are: Mutual Exclusion, Hold & Wait, No Preemption, and Circular Wait. "Preemption" (allowing resource preemption) actually prevents deadlock.',
    tags: ['os', 'deadlock', 'coffman'],
  },
  {
    title: 'OS Virtual Memory Thrashing',
    category: 'technical',
    subject: 'Operating System',
    topic: 'Virtual Memory',
    difficulty: 'hard',
    type: 'mcq',
    question: 'What causes Thrashing in an operating system?',
    options: [
      'Excessive page swapping when process working set exceeds available RAM',
      'CPU fan overheating',
      'Disk defragmentation failure',
      'Too many open sockets',
    ],
    correctAnswer: 'Excessive page swapping when process working set exceeds available RAM',
    explanation: 'Thrashing occurs when the OS spends more time swapping pages in/out of virtual memory than executing actual instructions.',
    tags: ['os', 'virtual-memory', 'thrashing'],
  },

  // ----- Computer Networks - Easy / Medium / Hard -----
  {
    title: 'TCP 3-Way Handshake Sequence',
    category: 'technical',
    subject: 'Computer Networks',
    topic: 'TCP/IP',
    difficulty: 'medium',
    type: 'mcq',
    question: 'What is the correct sequence of packets sent during a TCP 3-Way Handshake connection establishment?',
    options: ['SYN → SYN-ACK → ACK', 'SYN → ACK → SYN-ACK', 'ACK → SYN → ACK', 'FIN → ACK → FIN-ACK'],
    correctAnswer: 'SYN → SYN-ACK → ACK',
    explanation: 'Client sends SYN, Server responds with SYN-ACK, Client confirms with ACK to establish a reliable TCP socket connection.',
    tags: ['networking', 'tcp', 'handshake'],
  },
  {
    title: 'DNS Resolution Port & Protocol',
    category: 'technical',
    subject: 'Computer Networks',
    topic: 'DNS',
    difficulty: 'easy',
    type: 'mcq',
    question: 'Which transport protocol and port number are primarily used by standard DNS queries?',
    options: ['UDP Port 53', 'TCP Port 80', 'UDP Port 443', 'TCP Port 21'],
    correctAnswer: 'UDP Port 53',
    explanation: 'Standard DNS domain lookup queries use UDP Port 53 due to low overhead and speed.',
    tags: ['networking', 'dns', 'udp'],
  },
  {
    title: 'Subnetting CIDR Masking',
    category: 'technical',
    subject: 'Computer Networks',
    topic: 'IP Subnetting',
    difficulty: 'hard',
    type: 'mcq',
    question: 'How many usable host IP addresses are in a /26 IPv4 subnet?',
    options: ['62', '64', '126', '30'],
    correctAnswer: '62',
    explanation: '32 - 26 = 6 host bits. 2^6 = 64 addresses total. Subtract 2 (Network ID and Broadcast address) = 62 usable host IPs.',
    tags: ['networking', 'subnetting', 'ip'],
  },

  // =========================================================================
  // ===================== SECTION 3: DSA (30 Questions) =====================
  // =========================================================================

  // ----- Arrays & Strings -----
  {
    title: 'Two Sum Optimal Complexity',
    category: 'dsa',
    subject: 'Arrays',
    topic: 'Arrays',
    difficulty: 'easy',
    type: 'mcq',
    question: 'What is the time and space complexity of the optimal Hash Map approach for Two Sum?',
    options: ['Time O(N), Space O(N)', 'Time O(N²), Space O(1)', 'Time O(N log N), Space O(1)', 'Time O(1), Space O(N)'],
    correctAnswer: 'Time O(N), Space O(N)',
    explanation: 'Single pass hash table stores elements and looks up target complement in O(1) time per element.',
    tags: ['arrays', 'hashmap', 'two-sum'],
  },
  {
    title: 'Kadane\'s Algorithm Maximum Subarray',
    category: 'dsa',
    subject: 'Arrays',
    topic: 'Dynamic Programming',
    difficulty: 'medium',
    type: 'mcq',
    question: 'What is the time complexity of Kadane\'s algorithm for finding maximum contiguous subarray sum?',
    options: ['O(N)', 'O(N²)', 'O(N log N)', 'O(2^N)'],
    correctAnswer: 'O(N)',
    explanation: 'Kadane\'s algorithm maintains current local sum and global max in a single O(N) linear sweep.',
    tags: ['dsa', 'kadane', 'arrays'],
  },
  {
    title: 'Trapping Rain Water Algorithm',
    category: 'dsa',
    subject: 'Arrays',
    topic: 'Two Pointer',
    difficulty: 'hard',
    type: 'mcq',
    question: 'What is the optimal space complexity for the Trapping Rain Water problem using Two Pointers?',
    options: ['O(1)', 'O(N)', 'O(N²)', 'O(log N)'],
    correctAnswer: 'O(1)',
    explanation: 'By maintaining left_max and right_max with two inward pointers (left, right), we can solve it in O(N) time and O(1) auxiliary space.',
    tags: ['dsa', 'two-pointer', 'hard'],
  },
  {
    title: 'KMP Algorithm Prefix Function',
    category: 'dsa',
    subject: 'Strings',
    topic: 'String Matching',
    difficulty: 'hard',
    type: 'mcq',
    question: 'What is the worst-case time complexity of Knuth-Morris-Pratt (KMP) pattern matching algorithm for string of length N and pattern M?',
    options: ['O(N + M)', 'O(N × M)', 'O(N log M)', 'O(N²)'],
    correctAnswer: 'O(N + M)',
    explanation: 'KMP constructs an LPS (Longest Prefix Suffix) array in O(M) and searches in O(N), giving total O(N + M) worst-case efficiency.',
    tags: ['dsa', 'kmp', 'strings'],
  },

  // ----- Linked Lists -----
  {
    title: 'Floyd Cycle Detection (Tortoise and Hare)',
    category: 'dsa',
    subject: 'Linked List',
    topic: 'Cycle Detection',
    difficulty: 'easy',
    type: 'mcq',
    question: 'In Floyd\'s cycle detection algorithm for Linked List, slow moves 1 step. How many steps does fast pointer move?',
    options: ['2 steps', '3 steps', 'N steps', 'half step'],
    correctAnswer: '2 steps',
    explanation: 'Slow moves 1 step and fast moves 2 steps per iteration. If a cycle exists, they are guaranteed to meet inside the loop.',
    tags: ['linked-list', 'pointers', 'easy'],
  },
  {
    title: 'Reverse Linked List in Groups of K',
    category: 'dsa',
    subject: 'Linked List',
    topic: 'Pointer Manipulation',
    difficulty: 'hard',
    type: 'mcq',
    question: 'What is the time and auxiliary space complexity of reversing a linked list in k-group recursively?',
    options: ['Time O(N), Space O(N/k)', 'Time O(N²), Space O(1)', 'Time O(N log N), Space O(N)', 'Time O(N), Space O(N)'],
    correctAnswer: 'Time O(N), Space O(N/k)',
    explanation: 'Every node is visited constant times O(N), and recursive stack uses N/k frames O(N/k) space.',
    tags: ['linked-list', 'k-group', 'hard'],
  },

  // ----- Stack & Queue -----
  {
    title: 'Min Stack Constant Time O(1)',
    category: 'dsa',
    subject: 'Stack',
    topic: 'Stack Design',
    difficulty: 'medium',
    type: 'mcq',
    question: 'How can a stack return the minimum element in O(1) time?',
    options: [
      'By maintaining a secondary stack of current minimums alongside values',
      'By sorting the stack after every push',
      'By using a binary search tree',
      'By scanning all elements on min() call',
    ],
    correctAnswer: 'By maintaining a secondary stack of current minimums alongside values',
    explanation: 'An auxiliary min-stack stores current minimums at each depth, giving O(1) push, pop, top, and getMin.',
    tags: ['stack', 'min-stack', 'medium'],
  },
  {
    title: 'Sliding Window Maximum Monotonic Queue',
    category: 'dsa',
    subject: 'Queue',
    topic: 'Monotonic Queue',
    difficulty: 'hard',
    type: 'mcq',
    question: 'Which data structure allows computing sliding window maximum of array size N with window size K in O(N) total time?',
    options: ['Monotonic Double-ended Queue (Deque)', 'Max Heap', 'Balanced BST', 'Stack'],
    correctAnswer: 'Monotonic Double-ended Queue (Deque)',
    explanation: 'Monotonic Deque keeps indices in decreasing order of element values, pushing and popping each element at most once: O(N) time.',
    tags: ['deque', 'sliding-window', 'hard'],
  },

  // ----- Trees & Graphs -----
  {
    title: 'Binary Search Tree Search Complexity',
    category: 'dsa',
    subject: 'Trees',
    topic: 'Binary Search Tree',
    difficulty: 'easy',
    type: 'mcq',
    question: 'What is the worst-case time complexity of searching in an unbalanced (skewed) Binary Search Tree?',
    options: ['O(N)', 'O(log N)', 'O(1)', 'O(N log N)'],
    correctAnswer: 'O(N)',
    explanation: 'A skewed BST degenerates into a linked list, making search linear O(N). In balanced BST (AVL/Red-Black), it is O(log N).',
    tags: ['trees', 'bst', 'complexity'],
  },
  {
    title: 'Lowest Common Ancestor (LCA)',
    category: 'dsa',
    subject: 'Trees',
    topic: 'Binary Trees',
    difficulty: 'medium',
    type: 'mcq',
    question: 'What is the time complexity of finding LCA in a balanced binary tree using DFS recursion?',
    options: ['O(N)', 'O(N²)', 'O(1)', 'O(2^N)'],
    correctAnswer: 'O(N)',
    explanation: 'Post-order DFS visits each node at most once, taking linear O(N) time in worst case.',
    tags: ['trees', 'lca', 'dfs'],
  },
  {
    title: 'Dijkstra Shortest Path Algorithm',
    category: 'dsa',
    subject: 'Graphs',
    topic: 'Shortest Path',
    difficulty: 'medium',
    type: 'mcq',
    question: 'What is the time complexity of Dijkstra\'s algorithm using a Min-Priority Queue with Min-Heap for V vertices and E edges?',
    options: ['O((V + E) log V)', 'O(V²)', 'O(V × E)', 'O(E log E)'],
    correctAnswer: 'O((V + E) log V)',
    explanation: 'Using adjacency list + min-heap priority queue, vertex insertions take O(V log V) and edge relaxations take O(E log V) → O((V+E) log V).',
    tags: ['graphs', 'dijkstra', 'heap'],
  },
  {
    title: 'Topological Sort Applicability',
    category: 'dsa',
    subject: 'Graphs',
    topic: 'Topological Sort',
    difficulty: 'medium',
    type: 'mcq',
    question: 'Topological sorting is possible ONLY on which type of graphs?',
    options: ['Directed Acyclic Graphs (DAG)', 'Undirected Graphs', 'Cyclic Graphs', 'Complete Graphs'],
    correctAnswer: 'Directed Acyclic Graphs (DAG)',
    explanation: 'Topological sorting orders vertices linearly such that u precedes v for every directed edge u→v. It requires a Directed Acyclic Graph.',
    tags: ['graphs', 'dag', 'topological-sort'],
  },

  // ----- Dynamic Programming & Greedy -----
  {
    title: '0/1 Knapsack Time Complexity',
    category: 'dsa',
    subject: 'Dynamic Programming',
    topic: 'Knapsack',
    difficulty: 'hard',
    type: 'mcq',
    question: 'What is the time complexity of 0/1 Knapsack DP solution with N items and maximum capacity W?',
    options: ['O(N × W)', 'O(2^N)', 'O(N log W)', 'O(N + W)'],
    correctAnswer: 'O(N × W)',
    explanation: 'The 2D DP state table has dimensions N × W. Filling each cell takes O(1) operations, total time is pseudo-polynomial O(N × W).',
    tags: ['dp', 'knapsack', 'hard'],
  },
  {
    title: 'Fractional Knapsack Greedy Approach',
    category: 'dsa',
    subject: 'Greedy Algorithms',
    topic: 'Greedy',
    difficulty: 'easy',
    type: 'mcq',
    question: 'Which sorting strategy is used in the Fractional Knapsack problem?',
    options: [
      'Sort items by Value-to-Weight ratio in descending order',
      'Sort items by Weight in ascending order',
      'Sort items by Value in descending order',
      'Sort items randomly',
    ],
    correctAnswer: 'Sort items by Value-to-Weight ratio in descending order',
    explanation: 'Fractional Knapsack allows breaking items. Greedy strategy picks items with maximum value per unit weight (Value/Weight) first.',
    tags: ['greedy', 'knapsack', 'easy'],
  },

  // =========================================================================
  // ===================== SECTION 4: REAL CODING CHALLENGES (15 Questions) ===
  // =========================================================================
  {
    title: 'Two Sum',
    category: 'coding',
    subject: 'Arrays',
    topic: 'Hash Map',
    difficulty: 'easy',
    type: 'coding',
    question: 'Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.',
    correctAnswer: 'function twoSum(nums, target) {\n  const map = new Map();\n  for (let i = 0; i < nums.length; i++) {\n    const diff = target - nums[i];\n    if (map.has(diff)) return [map.get(diff), i];\n    map.set(nums[i], i);\n  }\n  return [];\n}',
    explanation: 'Use a hash map to store seen numbers and their indices. For each number, check if (target - number) is in the map.',
    constraints: '2 <= nums.length <= 10^4\n-10^9 <= nums[i] <= 10^9',
    sampleInput: 'nums = [2,7,11,15], target = 9',
    sampleOutput: '[0,1]',
    hints: ['Hash map lookup is O(1)'],
    solution: 'function twoSum(nums, target) {\n  const map = new Map();\n  for (let i = 0; i < nums.length; i++) {\n    const diff = target - nums[i];\n    if (map.has(diff)) return [map.get(diff), i];\n    map.set(nums[i], i);\n  }\n  return [];\n}',
    tags: ['leetcode-1', 'two-sum', 'hashmap'],
  },
  {
    title: 'Valid Parentheses',
    category: 'coding',
    subject: 'Stack',
    topic: 'Stack Matching',
    difficulty: 'easy',
    type: 'coding',
    question: 'Given a string s containing just the characters "(", ")", "{", "}", "[" and "]", determine if the input string is valid.',
    correctAnswer: 'function isValid(s) {\n  const stack = [];\n  const pairs = { ")": "(", "}": "{", "]": "[" };\n  for (let char of s) {\n    if (char in pairs) {\n      if (stack.pop() !== pairs[char]) return false;\n    } else {\n      stack.push(char);\n    }\n  }\n  return stack.length === 0;\n}',
    explanation: 'Push opening brackets to stack. When encountering a closing bracket, pop and verify it matches the expected opening bracket.',
    constraints: '1 <= s.length <= 10^4',
    sampleInput: 's = "()[]{}"',
    sampleOutput: 'true',
    hints: ['Last opened bracket must be closed first (LIFO)'],
    solution: 'function isValid(s) {\n  const stack = [];\n  const map = { ")": "(", "}": "{", "]": "[" };\n  for (let c of s) {\n    if (c in map) {\n      if (stack.pop() !== map[c]) return false;\n    } else {\n      stack.push(c);\n    }\n  }\n  return stack.length === 0;\n}',
    tags: ['leetcode-20', 'stack', 'strings'],
  },
  {
    title: 'Merge Two Sorted Lists',
    category: 'coding',
    subject: 'Linked List',
    topic: 'Two Pointer',
    difficulty: 'easy',
    type: 'coding',
    question: 'Merge two sorted linked lists list1 and list2 and return it as a sorted list.',
    correctAnswer: 'function mergeTwoLists(l1, l2) {\n  let dummy = new ListNode(0);\n  let current = dummy;\n  while (l1 && l2) {\n    if (l1.val <= l2.val) { current.next = l1; l1 = l1.next; }\n    else { current.next = l2; l2 = l2.next; }\n    current = current.next;\n  }\n  current.next = l1 || l2;\n  return dummy.next;\n}',
    explanation: 'Use a dummy head node and iteratively attach the smaller node from either list1 or list2.',
    constraints: '0 <= list length <= 50',
    sampleInput: 'l1 = [1,2,4], l2 = [1,3,4]',
    sampleOutput: '[1,1,2,3,4,4]',
    hints: ['Create a dummy sentinel node'],
    solution: 'function mergeTwoLists(l1, l2) {\n  let dummy = new ListNode(0);\n  let current = dummy;\n  while (l1 && l2) {\n    if (l1.val <= l2.val) { current.next = l1; l1 = l1.next; }\n    else { current.next = l2; l2 = l2.next; }\n    current = current.next;\n  }\n  current.next = l1 || l2;\n  return dummy.next;\n}',
    tags: ['leetcode-21', 'linked-list'],
  },
  {
    title: 'Maximum Subarray Sum',
    category: 'coding',
    subject: 'Dynamic Programming',
    topic: 'Kadane Algorithm',
    difficulty: 'medium',
    type: 'coding',
    question: 'Given an integer array nums, find the contiguous subarray (containing at least one number) which has the largest sum and return its sum.',
    correctAnswer: 'function maxSubArray(nums) {\n  let maxSum = nums[0];\n  let currentSum = nums[0];\n  for (let i = 1; i < nums.length; i++) {\n    currentSum = Math.max(nums[i], currentSum + nums[i]);\n    maxSum = Math.max(maxSum, currentSum);\n  }\n  return maxSum;\n}',
    explanation: 'Kadane\'s Algorithm: iterate and keep track of current contiguous subarray sum. If currentSum becomes negative, reset.',
    constraints: '1 <= nums.length <= 10^5',
    sampleInput: 'nums = [-2,1,-3,4,-1,2,1,-5,4]',
    sampleOutput: '6',
    hints: ['Kadane\'s algorithm runs in O(N)'],
    solution: 'function maxSubArray(nums) {\n  let maxSoFar = nums[0], currentMax = nums[0];\n  for (let i = 1; i < nums.length; i++) {\n    currentMax = Math.max(nums[i], currentMax + nums[i]);\n    maxSoFar = Math.max(maxSoFar, currentMax);\n  }\n  return maxSoFar;\n}',
    tags: ['leetcode-53', 'kadane', 'dp'],
  },
  {
    title: 'Longest Substring Without Repeating Characters',
    category: 'coding',
    subject: 'Strings',
    topic: 'Sliding Window',
    difficulty: 'medium',
    type: 'coding',
    question: 'Given a string s, find the length of the longest substring without repeating characters.',
    correctAnswer: 'function lengthOfLongestSubstring(s) {\n  let maxLen = 0, start = 0;\n  const map = new Map();\n  for (let i = 0; i < s.length; i++) {\n    if (map.has(s[i]) && map.get(s[i]) >= start) {\n      start = map.get(s[i]) + 1;\n    }\n    map.set(s[i], i);\n    maxLen = Math.max(maxLen, i - start + 1);\n  }\n  return maxLen;\n}',
    explanation: 'Sliding window technique with hash map storing last seen index of each character.',
    constraints: '0 <= s.length <= 5 * 10^4',
    sampleInput: 's = "abcabcbb"',
    sampleOutput: '3',
    hints: ['Dynamic window start pointer'],
    solution: 'function lengthOfLongestSubstring(s) {\n  let set = new Set(), left = 0, max = 0;\n  for (let right = 0; right < s.length; right++) {\n    while (set.has(s[right])) {\n      set.delete(s[left]);\n      left++;\n    }\n    set.add(s[right]);\n    max = Math.max(max, right - left + 1);\n  }\n  return max;\n}',
    tags: ['leetcode-3', 'sliding-window'],
  },
  {
    title: '3Sum Problem',
    category: 'coding',
    subject: 'Arrays',
    topic: 'Two Pointer',
    difficulty: 'medium',
    type: 'coding',
    question: 'Given an integer array nums, return all the triplets [nums[i], nums[j], nums[k]] such that i != j, i != k, and j != k, and nums[i] + nums[j] + nums[k] == 0.',
    correctAnswer: 'function threeSum(nums) {\n  nums.sort((a, b) => a - b);\n  const res = [];\n  for (let i = 0; i < nums.length - 2; i++) {\n    if (i > 0 && nums[i] === nums[i - 1]) continue;\n    let left = i + 1, right = nums.length - 1;\n    while (left < right) {\n      const sum = nums[i] + nums[left] + nums[right];\n      if (sum === 0) {\n        res.push([nums[i], nums[left], nums[right]]);\n        while (left < right && nums[left] === nums[left + 1]) left++;\n        while (left < right && nums[right] === nums[right - 1]) right--;\n        left++; right--;\n      } else if (sum < 0) left++;\n      else right--;\n    }\n  }\n  return res;\n}',
    explanation: 'Sort the array first. For each element, use two pointers (left and right) on the remaining array to find sum zero, skipping duplicates.',
    constraints: '3 <= nums.length <= 3000',
    sampleInput: 'nums = [-1,0,1,2,-1,-4]',
    sampleOutput: '[[-1,-1,2],[-1,0,1]]',
    hints: ['Sort array first then use two pointer approach'],
    solution: 'function threeSum(nums) {\n  nums.sort((a, b) => a - b);\n  const res = [];\n  for (let i = 0; i < nums.length - 2; i++) {\n    if (i > 0 && nums[i] === nums[i - 1]) continue;\n    let left = i + 1, right = nums.length - 1;\n    while (left < right) {\n      const sum = nums[i] + nums[left] + nums[right];\n      if (sum === 0) {\n        res.push([nums[i], nums[left], nums[right]]);\n        while (left < right && nums[left] === nums[left + 1]) left++;\n        while (left < right && nums[right] === nums[right - 1]) right--;\n        left++; right--;\n      } else if (sum < 0) left++;\n      else right--;\n    }\n  }\n  return res;\n}',
    tags: ['leetcode-15', '3sum', 'two-pointer'],
  },
  {
    title: 'LRU Cache Design',
    category: 'coding',
    subject: 'Data Structures',
    topic: 'Doubly Linked List & Hash Map',
    difficulty: 'hard',
    type: 'coding',
    question: 'Design a data structure that follows the constraints of a Least Recently Used (LRU) cache with get(key) and put(key, value) operations in O(1) time complexity.',
    correctAnswer: 'class LRUCache {\n  constructor(capacity) {\n    this.capacity = capacity;\n    this.map = new Map(); // Preserves insertion order in JS\n  }\n  get(key) {\n    if (!this.map.has(key)) return -1;\n    const val = this.map.get(key);\n    this.map.delete(key);\n    this.map.set(key, val);\n    return val;\n  }\n  put(key, value) {\n    if (this.map.has(key)) this.map.delete(key);\n    this.map.set(key, value);\n    if (this.map.size > this.capacity) {\n      const firstKey = this.map.keys().next().value;\n      this.map.delete(firstKey);\n    }\n  }\n}',
    explanation: 'In JavaScript Map preserves insertion order. Deleting and re-setting moves an key to the most recently used end in O(1) time.',
    constraints: '1 <= capacity <= 3000',
    sampleInput: 'LRUCache(2); put(1,1); put(2,2); get(1); put(3,3); get(2);',
    sampleOutput: 'get(1)->1, get(2)->-1 (evicted)',
    hints: ['Combine Hash Table with Doubly Linked List'],
    solution: 'class LRUCache {\n  constructor(capacity) {\n    this.capacity = capacity;\n    this.map = new Map();\n  }\n  get(key) {\n    if (!this.map.has(key)) return -1;\n    const val = this.map.get(key);\n    this.map.delete(key);\n    this.map.set(key, val);\n    return val;\n  }\n  put(key, value) {\n    if (this.map.has(key)) this.map.delete(key);\n    this.map.set(key, value);\n    if (this.map.size > this.capacity) {\n      const firstKey = this.map.keys().next().value;\n      this.map.delete(firstKey);\n    }\n  }\n}',
    tags: ['leetcode-146', 'lru', 'design'],
  },

  // =========================================================================
  // ===================== SECTION 5: MOCK INTERVIEW HR/BEHAVIORAL (15 Questions) =
  // =========================================================================
  {
    title: 'Tell Me About Yourself',
    category: 'hr',
    subject: 'HR',
    topic: 'Introduction',
    difficulty: 'easy',
    type: 'subjective',
    question: 'Tell me about yourself and your background.',
    correctAnswer: 'Structure using Present, Past, Future formula: 1) Present role/education, 2) Relevant key projects & tech stack skills, 3) Why you are passionate about this role.',
    explanation: 'Keep it concise (90-120 seconds). Connect your educational and technical achievements to the company\'s mission.',
    tags: ['hr', 'introduction', 'basics'],
  },
  {
    title: 'Strengths and Weaknesses',
    category: 'hr',
    subject: 'HR',
    topic: 'Self Awareness',
    difficulty: 'easy',
    type: 'subjective',
    question: 'What is your greatest technical strength, and what is one area you are trying to improve?',
    correctAnswer: 'Strength: Pick a technical skill backed by a specific project metric. Weakness: Pick a real minor weakness and demonstrate concrete actionable steps you are taking to overcome it.',
    explanation: 'Avoid humblebrags like "I work too hard". Show real self-awareness and active growth mindset.',
    tags: ['hr', 'self-assessment'],
  },
  {
    title: 'Why Do You Want to Work at Our Company?',
    category: 'hr',
    subject: 'HR',
    topic: 'Company Knowledge',
    difficulty: 'medium',
    type: 'subjective',
    question: 'Why do you want to join our organization specifically?',
    correctAnswer: 'Reference 1) Recent products/engineering blogs of the company, 2) Alignment with tech stack, 3) How your values match their engineering culture.',
    explanation: 'Demonstrate genuine research about the company. Show enthusiasm for their technical challenges.',
    tags: ['hr', 'motivation'],
  },
  {
    title: 'Describe a Challenging Technical Problem (STAR Method)',
    category: 'behavioral',
    subject: 'Behavioral',
    topic: 'Problem Solving',
    difficulty: 'medium',
    type: 'subjective',
    question: 'Tell me about a complex bug or performance bottleneck you encountered in a project and how you resolved it.',
    correctAnswer: 'STAR Method: Situation (project context), Task (the bug/bottleneck), Action (debugging tools used like Chrome DevTools/profiler, root cause analysis, fix implemented), Result (performance improvement % or stability gained).',
    explanation: 'Focus heavily on the Action step — explain your thought process and problem-solving methodology.',
    tags: ['behavioral', 'star-method', 'debugging'],
  },
  {
    title: 'Handling Technical Disagreements in a Team',
    category: 'behavioral',
    subject: 'Behavioral',
    topic: 'Conflict Resolution',
    difficulty: 'medium',
    type: 'subjective',
    question: 'Describe a situation where you disagreed with a teammate regarding technical architecture or implementation decisions. How did you handle it?',
    correctAnswer: '1) Active listening to understand their perspective, 2) Benchmarking / prototyping both solutions with data, 3) Deciding based on trade-offs and team alignment rather than ego.',
    explanation: 'Focus on data-driven decision making, humility, and keeping team goals first.',
    tags: ['behavioral', 'teamwork', 'conflict'],
  },
  {
    title: 'Handling Tight Deadlines Under Pressure',
    category: 'behavioral',
    subject: 'Behavioral',
    topic: 'Pressure Management',
    difficulty: 'easy',
    type: 'subjective',
    question: 'How do you handle high-pressure situations or sudden shifting project scope deadlines?',
    correctAnswer: 'Explain prioritization (MoSCoW method), proactive communication with stakeholders, breaking tasks into deliverables, and staying calm.',
    explanation: 'Highlight clear communication and structured workload management.',
    tags: ['behavioral', 'stress', 'deadlines'],
  },
  {
    title: 'Handling Failure or Project Mistakes',
    category: 'behavioral',
    subject: 'Behavioral',
    topic: 'Growth Mindset',
    difficulty: 'hard',
    type: 'subjective',
    question: 'Tell me about a time a software deployment or project failed. What happened and what did you learn?',
    correctAnswer: '1) Own the mistake directly, 2) Explain immediate mitigation steps taken, 3) Explain post-mortem root cause analysis and systemic prevention put in place (e.g., CI/CD tests, validation checks).',
    explanation: 'Interviews value accountability and post-mortem continuous improvement over pretending to be flawless.',
    tags: ['behavioral', 'failure', 'ownership'],
  },
  {
    title: 'System Design Mock Intro Question',
    category: 'technical',
    subject: 'System Design',
    topic: 'Architecture',
    difficulty: 'hard',
    type: 'subjective',
    question: 'How would you design a scalable URL Shortener service (like bit.ly)? Discuss Database, Hashing, and Caching.',
    correctAnswer: '1) Functional requirements (shorten link, redirect), 2) Estimation & Scale, 3) Base62 Encoding of auto-increment ID, 4) Redis caching for popular links, 5) DB choice (NoSQL / SQL indexed by shortcode).',
    explanation: 'Structure system design systematically: Requirements -> High Level Architecture -> Deep Dive -> Bottlenecks & Caching.',
    tags: ['system-design', 'architecture', 'mock-interview'],
  }
];

const seedDB = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('✅ Connected to MongoDB');

    // Clear existing data
    await Question.deleteMany({});
    console.log('🗑️  Cleared existing questions');

    // Insert questions
    const insertedQuestions = await Question.insertMany(questions);
    console.log(`✅ Successfully seeded ${insertedQuestions.length} real interview questions!`);

    // Create demo users if not present
    const existingAdmin = await User.findOne({ email: 'admin@placementpro.com' });
    if (!existingAdmin) {
      await User.create({
        name: 'Admin User',
        email: 'admin@placementpro.com',
        password: 'admin123456',
        role: 'admin',
        college: 'PlacementPro University',
        branch: 'Computer Science',
        graduationYear: 2025,
        badges: ['newcomer', 'admin'],
        achievements: ['Registered on PlacementPro', 'Admin privileges granted'],
      });
      console.log('✅ Created admin user (admin@placementpro.com / admin123456)');
    }

    const existingUser = await User.findOne({ email: 'demo@placementpro.com' });
    if (!existingUser) {
      await User.create({
        name: 'Demo Student',
        email: 'demo@placementpro.com',
        password: 'demo123456',
        college: 'IIT Delhi',
        branch: 'Computer Science',
        graduationYear: 2025,
        badges: ['newcomer'],
        achievements: ['Registered on PlacementPro'],
      });
      console.log('✅ Created demo user (demo@placementpro.com / demo123456)');
    }

    console.log('\n🎉 PlacementPro Database Seeding Complete!');
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    console.log('Admin Login: admin@placementpro.com / admin123456');
    console.log('Demo Login:  demo@placementpro.com / demo123456');
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');

    process.exit(0);
  } catch (error) {
    console.error('❌ Seeding error:', error.message);
    process.exit(1);
  }
};

seedDB();
